<?xml version="1.0" encoding="UTF-8"?>
<pattern id="EFORMS-validation-stage-4-28" xmlns="http://purl.oclc.org/dsdl/schematron">
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='accessibility']">
        <assert id="R-43M-6BY" role="ERROR" diagnostics="ND-AccessibilityJustification_BT-755-Lot" test="(not(cbc:ProcurementType)) or (not(not(cbc:ProcurementTypeCode/normalize-space(text()) = 'n-inc-just')))">rule|text|R-43M-6BY</assert>
        <assert id="R-IP8-TT8" role="ERROR" diagnostics="ND-AccessibilityJustification_BT-755-Lot" test="(cbc:ProcurementType) or (not(cbc:ProcurementTypeCode/normalize-space(text()) = 'n-inc-just'))">rule|text|R-IP8-TT8</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:Change">
        <assert id="R-KCK-FII" role="ERROR" diagnostics="ND-Change_BT-141_a_-notice" test="(not(efbc:ChangeDescription)) or (not(not(efac:ChangedSection/efbc:ChangedSectionIdentifier)))">rule|text|R-KCK-FII</assert>
        <assert id="R-1NG-MG0" role="ERROR" diagnostics="ND-Change_BT-718-notice" test="(not(efbc:ProcurementDocumentsChangeIndicator)) or (not(not(efac:ChangedSection/efbc:ChangedSectionIdentifier)))">rule|text|R-1NG-MG0</assert>
        <assert id="R-5EZ-3OO" role="ERROR" diagnostics="ND-Change_BT-719-notice" test="(not(efbc:ProcurementDocumentsChangeDate)) or (not(not(efbc:ProcurementDocumentsChangeIndicator = true())))">rule|text|R-5EZ-3OO</assert>
        <assert id="R-MSX-Q3H" role="ERROR" diagnostics="ND-Change_BT-719-notice" test="(efbc:ProcurementDocumentsChangeDate) or (not(efbc:ProcurementDocumentsChangeIndicator = true()))">rule|text|R-MSX-Q3H</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:Change/efac:ChangedSection">
        <assert id="R-TC6-DR2" role="ERROR" diagnostics="ND-ChangedSection_BT-13716-notice" test="(not(efbc:ChangedSectionIdentifier)) or (not(not(../../efbc:ChangedNoticeIdentifier)))">rule|text|R-TC6-DR2</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company">
        <assert id="R-5DD-4SZ" role="ERROR" diagnostics="ND-Company_BT-165-Organization-Company" test="(not(efbc:CompanySizeCode)) or (not(not(cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../efac:NoticeResult/efac:TenderingParty/efac:Tenderer/cbc:ID/normalize-space(text())) and not(cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../efac:NoticeResult/efac:TenderingParty/efac:SubContractor/cbc:ID/normalize-space(text()))))">rule|text|R-5DD-4SZ</assert>
        <assert id="R-2YU-B6H" role="ERROR" diagnostics="ND-Company_BT-503-Organization-Company" test="(cac:Contact/cbc:Telephone) or (not((cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text()))))">rule|text|R-2YU-B6H</assert>
        <assert id="R-W63-KCM" role="ERROR" diagnostics="ND-Company_BT-506-Organization-Company" test="(cac:Contact/cbc:ElectronicMail) or (not((cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text()))))">rule|text|R-W63-KCM</assert>
        <assert id="R-IM0-8CV" role="ERROR" diagnostics="ND-Company_BT-507-Organization-Company" test="(not(cac:PostalAddress/cbc:CountrySubentityCode)) or (not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('ALB','AUT','BEL','BGR','CHE','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ISL','ITA','LIE','LTU','LUX','LVA','MKD','MLT','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE','TUR','UKR','XKX'))))">rule|text|R-IM0-8CV</assert>
        <assert id="R-6L0-71L" role="ERROR" diagnostics="ND-Company_BT-507-Organization-Company" test="(cac:PostalAddress/cbc:CountrySubentityCode) or (not(not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('ALB','AUT','BEL','BGR','CHE','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ISL','ITA','LIE','LTU','LUX','LVA','MKD','MLT','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE','TUR','UKR','XKX')))))">rule|text|R-6L0-71L</assert>
        <assert id="R-VJQ-ZSG" role="ERROR" diagnostics="ND-Company_BT-510_a_-Organization-Company" test="(not(cac:PostalAddress/cbc:StreetName)) or (not(not(cac:PostalAddress/cbc:CityName)))">rule|text|R-VJQ-ZSG</assert>
        <assert id="R-6RV-RSQ" role="ERROR" diagnostics="ND-Company_BT-510_b_-Organization-Company" test="(not(cac:PostalAddress/cbc:AdditionalStreetName)) or (not(not(cac:PostalAddress/cbc:StreetName)))">rule|text|R-6RV-RSQ</assert>
        <assert id="R-OS0-QIK" role="ERROR" diagnostics="ND-Company_BT-510_c_-Organization-Company" test="(not(cac:PostalAddress/cac:AddressLine/cbc:Line)) or (not(not(cac:PostalAddress/cbc:AdditionalStreetName)))">rule|text|R-OS0-QIK</assert>
        <assert id="R-OO2-8CS" role="ERROR" diagnostics="ND-Company_BT-512-Organization-Company" test="(cac:PostalAddress/cbc:PostalZone) or (not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('AFG','ALA','ALB','AND','ARG','ARM','AUS','AUT','AZE','BEL','BGD','BGR','BHR','BIH','BLM','BLR','BMU','BRA','BRB','BRN','BTN','CAN','CHE','CHL','CHN','COL','CPT','CPV','CRI','CUB','CYM','CYP','CZE','DEU','DJI','DNK','DOM','DZA','ECU','EGY','ESP','EST','ETH','FIN','FRA','FRO','FSM','GBR','GEO','GGY','GIN','GNB','GRC','GRL','GTM','GUM','HND','HRV','HTI','HUN','IDN','IMN','IND','IRL','IRN','IRQ','ISL','ISR','ITA','JEY','JOR','JPN','KAZ','KEN','KGZ','KHM','KIR','KOR','KWT','LAO','LBN','LIE','LKA','LSO','LTU','LUX','LVA','MAF','MAR','MCO','MDA','MDG','MDV','MEX','MHL','MLT','MMR','MNE','MNG','MOZ','MSR','MUS','MWI','MYS','NAM','NCL','NER','NGA','NIC','NLD','NOR','NPL','NRU','NZL','OMN','PAK','PER','PHL','PNG','POL','PRI','PRT','PRY','PSE','PYF','ROU','RUS','SAU','SDN','SEN','SGP','SJM','SLV','SMR','SPM','SRB','SVK','SVN','SWE','SWZ','THA','TJK','TKM','TLS','TTO','TUN','TUR','UKR','URY','USA','UZB','VCT','VEN','VGB','VIR','VNM','WLF','ZAF')))">rule|text|R-OO2-8CS</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:SettledContract/efac:Funding">
        <assert id="R-06X-2FB" role="ERROR" diagnostics="ND-ContractEUFunds_BT-6110-Contract" test="(not(cbc:Description)) or (not(not(cbc:FundingProgramCode) and not(efbc:FinancingIdentifier)))">rule|text|R-06X-2FB</assert>
    </rule>
    <rule context="/*/cac:ContractingParty">
        <assert id="R-DHU-YHE" role="ERROR" diagnostics="ND-ContractingParty_BT-10-Procedure-Buyer" test="(not(cac:ContractingActivity[cbc:ActivityTypeCode/@listName='authority-activity']/cbc:ActivityTypeCode[@listName='authority-activity'])) or (not(not(cac:ContractingPartyType[cbc:PartyTypeCode/@listName='buyer-legal-type']/cbc:PartyTypeCode[@listName='buyer-legal-type']/normalize-space(text()) = ('body-pl','body-pl-cga','body-pl-la','body-pl-ra','cga','def-cont','eu-ins-bod-ag','int-org','la','org-sub','org-sub-cga','org-sub-la','org-sub-ra','ra'))))">rule|text|R-DHU-YHE</assert>
        <assert id="R-HQF-PUD" role="ERROR" diagnostics="ND-ContractingParty_BT-610-Procedure-Buyer" test="(not(cac:ContractingActivity[cbc:ActivityTypeCode/@listName='entity-activity']/cbc:ActivityTypeCode[@listName='entity-activity'])) or (not(not(cac:ContractingPartyType[cbc:PartyTypeCode/@listName='buyer-legal-type']/cbc:PartyTypeCode[@listName='buyer-legal-type']/normalize-space(text()) = ('pub-undert','pub-undert-cga','pub-undert-la','pub-undert-ra','spec-rights-entity'))))">rule|text|R-HQF-PUD</assert>
    </rule>
    <rule context="/*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[cbc:ID/text()='CrossBorderLaw']">
        <assert id="R-0O3-06F" role="ERROR" diagnostics="ND-CrossBorderLaw_BT-09_b_-Procedure" test="(not(cbc:DocumentDescription)) or (not(not(cbc:ID)))">rule|text|R-0O3-06F</assert>
        <assert id="R-OVZ-GEM" role="ERROR" diagnostics="ND-CrossBorderLaw_BT-09_b_-Procedure" test="(cbc:DocumentDescription) or (not(not(not(cbc:ID))))">rule|text|R-OVZ-GEM</assert>
    </rule>
    <rule context="/*/cac:TenderingProcess/cac:ProcessJustification[cbc:ProcessReasonCode/@listName='direct-award-justification']">
        <assert id="R-9KB-RN0" role="ERROR" diagnostics="ND-DirectAward_BT-135-Procedure" test="(not(cbc:ProcessReason)) or (not(not(cbc:ProcessReasonCode)))">rule|text|R-9KB-RN0</assert>
        <assert id="R-TIM-FW1" role="ERROR" diagnostics="ND-DirectAward_BT-135-Procedure" test="(cbc:ProcessReason) or (not(not(not(cbc:ProcessReasonCode))))">rule|text|R-TIM-FW1</assert>
    </rule>
    <rule context="/*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[cbc:ID/text()='LocalLegalBasis']">
        <assert id="R-WSW-QCT" role="ERROR" diagnostics="ND-LocalLegalBasisNoID_BT-01_f_-Procedure" test="(not(cbc:DocumentDescription)) or (not(not(cbc:ID)))">rule|text|R-WSW-QCT</assert>
        <assert id="R-S4N-ELQ" role="ERROR" diagnostics="ND-LocalLegalBasisNoID_BT-01_f_-Procedure" test="(cbc:DocumentDescription) or (not(not(not(cbc:ID))))">rule|text|R-S4N-ELQ</assert>
    </rule>
    <rule context="/*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[not(cbc:ID/text()=('CrossBorderLaw','LocalLegalBasis'))]">
        <assert id="R-MA8-D75" role="ERROR" diagnostics="ND-LocalLegalBasisWithID_BT-01_d_-Procedure" test="(not(cbc:DocumentDescription)) or (not(not(cbc:ID)))">rule|text|R-MA8-D75</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:AdditionalCommodityClassification">
        <assert id="R-G9R-HCI" role="ERROR" diagnostics="ND-LotAdditionalClassification_BT-26_a_-Lot" test="(not(cbc:ItemClassificationCode/@listName)) or (not(not(cbc:ItemClassificationCode)))">rule|text|R-G9R-HCI</assert>
        <assert id="R-ZA1-JTF" role="ERROR" diagnostics="ND-LotAdditionalClassification_BT-26_a_-Lot" test="(cbc:ItemClassificationCode/@listName) or (not(not(not(cbc:ItemClassificationCode))))">rule|text|R-ZA1-JTF</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion">
        <assert id="R-KN0-MRC" role="ERROR" diagnostics="ND-LotAwardCriteria_BT-543-Lot" test="(not(cbc:CalculationExpression)) or (not((cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric) or (cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']/efbc:ParameterNumeric) or (cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']/efbc:ParameterNumeric)))">rule|text|R-KN0-MRC</assert>
        <assert id="R-RR0-I1J" role="ERROR" diagnostics="ND-LotAwardCriteria_BT-733-Lot" test="(not(cbc:Description)) or (not(not(some $x in cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterCode/normalize-space(text()) satisfies $x = 'ord-imp')))">rule|text|R-RR0-I1J</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion">
        <assert id="R-FRA-8G5" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-540-Lot" test="(not(cbc:Description)) or (not(not(cbc:AwardingCriterionTypeCode[@listName='award-criterion-type'])))">rule|text|R-FRA-8G5</assert>
        <assert id="R-DTD-D7Q" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-540-Lot" test="(cbc:Description) or (not(not(not(cbc:AwardingCriterionTypeCode[@listName='award-criterion-type']))))">rule|text|R-DTD-D7Q</assert>
        <assert id="R-08L-0I0" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-541-Lot-FixedNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-08L-0I0</assert>
        <assert id="R-9XX-CIL" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-541-Lot-ThresholdNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-9XX-CIL</assert>
        <assert id="R-75C-BP4" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-541-Lot-WeightNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-75C-BP4</assert>
        <assert id="R-NWB-0K9" role="ERROR" diagnostics="ND-LotAwardCriterion_BT-734-Lot" test="(not(cbc:Name)) or (not(not(cbc:Description)))">rule|text|R-NWB-0K9</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']">
        <assert id="R-E5Z-UY9" role="ERROR" diagnostics="ND-LotAwardFixedCriterionParameter_BT-5422-Lot" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-E5Z-UY9</assert>
        <assert id="R-ZCJ-DRX" role="ERROR" diagnostics="ND-LotAwardFixedCriterionParameter_BT-5422-Lot" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-ZCJ-DRX</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']">
        <assert id="R-5XN-Y5L" role="ERROR" diagnostics="ND-LotAwardThresholdCriterionParameter_BT-5423-Lot" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-5XN-Y5L</assert>
        <assert id="R-RJL-RC3" role="ERROR" diagnostics="ND-LotAwardThresholdCriterionParameter_BT-5423-Lot" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-RJL-RC3</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']">
        <assert id="R-F0J-L83" role="ERROR" diagnostics="ND-LotAwardWeightCriterionParameter_BT-5421-Lot" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-F0J-L83</assert>
        <assert id="R-33R-AJ7" role="ERROR" diagnostics="ND-LotAwardWeightCriterionParameter_BT-5421-Lot" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-33R-AJ7</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:PlannedPeriod">
        <assert id="R-YHB-8ZE" role="ERROR" diagnostics="ND-LotDuration_BT-36-Lot" test="(not(cbc:DurationMeasure)) or (not((cbc:EndDate and cbc:StartDate) or (cbc:DescriptionCode)))">rule|text|R-YHB-8ZE</assert>
        <assert id="R-05Y-W04" role="ERROR" diagnostics="ND-LotDuration_BT-536-Lot" test="(not(cbc:StartDate)) or (not((cbc:DurationMeasure and cbc:EndDate) or (cbc:DescriptionCode and cbc:EndDate)))">rule|text|R-05Y-W04</assert>
        <assert id="R-PJF-HTA" role="ERROR" diagnostics="ND-LotDuration_BT-537-Lot" test="(not(cbc:EndDate)) or (not((cbc:StartDate and cbc:DescriptionCode) or (cbc:StartDate and cbc:DurationMeasure) or (cbc:DescriptionCode and cbc:DescriptionCode/normalize-space(text()) = 'UNLIMITED')))">rule|text|R-PJF-HTA</assert>
        <assert id="R-9P9-EF3" role="ERROR" diagnostics="ND-LotDuration_BT-538-Lot" test="(not(cbc:DescriptionCode)) or (not(cbc:DurationMeasure or (cbc:EndDate and cbc:StartDate)))">rule|text|R-9P9-EF3</assert>
        <assert id="R-34M-B6S" role="ERROR" diagnostics="ND-LotDuration_OPA-36-Lot-Number" test="(not(cbc:DurationMeasure)) or (not((cbc:EndDate and cbc:StartDate) or (cbc:DescriptionCode)))">rule|text|R-34M-B6S</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:MainCommodityClassification">
        <assert id="R-MKV-GB2" role="ERROR" diagnostics="ND-LotMainClassification_BT-26_m_-Lot" test="(not(cbc:ItemClassificationCode/@listName)) or (not(not(cbc:ItemClassificationCode)))">rule|text|R-MKV-GB2</assert>
        <assert id="R-FMV-V7N" role="ERROR" diagnostics="ND-LotMainClassification_BT-26_m_-Lot" test="(cbc:ItemClassificationCode/@listName) or (not(not(not(cbc:ItemClassificationCode))))">rule|text|R-FMV-V7N</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation">
        <assert id="R-N4S-3M1" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5071-Lot" test="(not(cac:Address/cbc:CountrySubentityCode)) or (not(cac:Address/cbc:Region or not(cac:Address/cac:Country/cbc:IdentificationCode)))">rule|text|R-N4S-3M1</assert>
        <assert id="R-LJ6-0DS" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5101_a_-Lot" test="(not(cac:Address/cbc:StreetName)) or (not(not(cac:Address/cbc:CityName)))">rule|text|R-LJ6-0DS</assert>
        <assert id="R-1LK-P87" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5101_b_-Lot" test="(not(cac:Address/cbc:AdditionalStreetName)) or (not(not(cac:Address/cbc:StreetName)))">rule|text|R-1LK-P87</assert>
        <assert id="R-GLF-8CI" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5101_c_-Lot" test="(not(cac:Address/cac:AddressLine/cbc:Line)) or (not(not(cac:Address/cbc:AdditionalStreetName)))">rule|text|R-GLF-8CI</assert>
        <assert id="R-M0R-60V" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5121-Lot" test="(not(cac:Address/cbc:PostalZone)) or (not(not(cac:Address/cbc:CityName)))">rule|text|R-M0R-60V</assert>
        <assert id="R-917-8WO" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5121-Lot" test="(cac:Address/cbc:PostalZone) or (not(cac:Address/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('AFG','ALA','ALB','AND','ARG','ARM','AUS','AUT','AZE','BEL','BGD','BGR','BHR','BIH','BLM','BLR','BMU','BRA','BRB','BRN','BTN','CAN','CHE','CHL','CHN','COL','CPT','CPV','CRI','CUB','CYM','CYP','CZE','DEU','DJI','DNK','DOM','DZA','ECU','EGY','ESP','EST','ETH','FIN','FRA','FRO','FSM','GBR','GEO','GGY','GIN','GNB','GRC','GRL','GTM','GUM','HND','HRV','HTI','HUN','IDN','IMN','IND','IRL','IRN','IRQ','ISL','ISR','ITA','JEY','JOR','JPN','KAZ','KEN','KGZ','KHM','KIR','KOR','KWT','LAO','LBN','LIE','LKA','LSO','LTU','LUX','LVA','MAF','MAR','MCO','MDA','MDG','MDV','MEX','MHL','MLT','MMR','MNE','MNG','MOZ','MSR','MUS','MWI','MYS','NAM','NCL','NER','NGA','NIC','NLD','NOR','NPL','NRU','NZL','OMN','PAK','PER','PHL','PNG','POL','PRI','PRT','PRY','PSE','PYF','ROU','RUS','SAU','SDN','SEN','SGP','SJM','SLV','SMR','SPM','SRB','SVK','SVN','SWE','SWZ','THA','TJK','TKM','TLS','TTO','TUN','TUR','UKR','URY','USA','UZB','VCT','VEN','VGB','VIR','VNM','WLF','ZAF') and cac:Address/cbc:StreetName))">rule|text|R-917-8WO</assert>
        <assert id="R-2AL-NB1" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-5131-Lot" test="(not(cac:Address/cbc:CityName)) or (not(cac:Address/cbc:Region or not(cac:Address/cac:Country/cbc:IdentificationCode)))">rule|text|R-2AL-NB1</assert>
        <assert id="R-62V-ADZ" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-728-Lot" test="(not(cbc:Description)) or (not(not(cac:Address/cbc:Region) and not(cac:Address/cac:Country/cbc:IdentificationCode)))">rule|text|R-62V-ADZ</assert>
        <assert id="R-IB3-9L3" role="ERROR" diagnostics="ND-LotPlacePerformance_BT-728-Lot" test="(cbc:Description) or (not((not(cac:Address/cbc:Region)) and (not(cac:Address/cbc:CountrySubentityCode)) and (not(cac:Address/cbc:CityName))))">rule|text|R-IB3-9L3</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject">
        <assert id="R-BEM-4LX" role="ERROR" diagnostics="ND-LotProcurementScope_BT-531-Lot" test="(not(cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='contract-nature']/cbc:ProcurementTypeCode)) or (not(not(cbc:ProcurementTypeCode[@listName='contract-nature'])))">rule|text|R-BEM-4LX</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender">
        <assert id="R-GSB-K49" role="ERROR" diagnostics="ND-LotTender_BT-13714-Tender" test="(not(efac:TenderLot/cbc:ID)) or (not(not(efac:TenderReference/cbc:ID)))">rule|text|R-GSB-K49</assert>
        <assert id="R-3QI-0OB" role="ERROR" diagnostics="ND-LotTender_BT-13714-Tender" test="(efac:TenderLot/cbc:ID) or (not(not(not(efac:TenderReference/cbc:ID))))">rule|text|R-3QI-0OB</assert>
        <assert id="R-NT7-EHB" role="ERROR" diagnostics="ND-LotTender_BT-160-Tender" test="(not(efac:ConcessionRevenue/efbc:RevenueBuyerAmount)) or (not(not(cbc:ID)))">rule|text|R-NT7-EHB</assert>
        <assert id="R-X4I-8R8" role="ERROR" diagnostics="ND-LotTender_BT-162-Tender" test="(not(efac:ConcessionRevenue/efbc:RevenueUserAmount)) or (not(not(cbc:ID)))">rule|text|R-X4I-8R8</assert>
        <assert id="R-B59-VBU" role="ERROR" diagnostics="ND-LotTender_BT-163-Tender" test="(not(efac:ConcessionRevenue/efbc:ValueDescription)) or (not(not(cbc:ID)))">rule|text|R-B59-VBU</assert>
        <assert id="R-NFG-Q6C" role="ERROR" diagnostics="ND-LotTender_BT-3201-Tender" test="(not(efac:TenderReference/cbc:ID)) or (not(not(cbc:ID)))">rule|text|R-NFG-Q6C</assert>
        <assert id="R-YJ6-29D" role="ERROR" diagnostics="ND-LotTender_BT-3201-Tender" test="(efac:TenderReference/cbc:ID) or (not(not(not(cbc:ID))))">rule|text|R-YJ6-29D</assert>
        <assert id="R-Y99-JBR" role="ERROR" diagnostics="ND-LotTender_BT-773-Tender" test="(not(efac:SubcontractingTerm[efbc:TermCode/@listName='applicability']/efbc:TermCode)) or (not(not(cbc:ID)))">rule|text|R-Y99-JBR</assert>
        <assert id="R-Q53-JFM" role="ERROR" diagnostics="ND-LotTender_OPT-310-Tender" test="(not(efac:TenderingParty/cbc:ID)) or (not(not(cbc:ID)))">rule|text|R-Q53-JFM</assert>
        <assert id="R-EFD-W2R" role="ERROR" diagnostics="ND-LotTender_OPT-310-Tender" test="(efac:TenderingParty/cbc:ID) or (not(not(not(cbc:ID))))">rule|text|R-EFD-W2R</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess">
        <assert id="R-UUO-4OO" role="ERROR" diagnostics="ND-LotTenderingProcess_BT-1251-Lot" test="(not(cac:NoticeDocumentReference/cbc:ReferencedDocumentInternalAddress)) or (not(not(cac:NoticeDocumentReference/cbc:ID)))">rule|text|R-UUO-4OO</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']">
        <assert id="R-BF8-8AZ" role="ERROR" diagnostics="ND-LotsGroup_BT-137-LotsGroup" test="(not(cbc:ID)) or (not(count(/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cbc:ID/normalize-space(text())) &lt; 2))">rule|text|R-BF8-8AZ</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion">
        <assert id="R-Z81-MNC" role="ERROR" diagnostics="ND-LotsGroupAwardCriteria_BT-539-LotsGroup" test="(not(cac:SubordinateAwardingCriterion/cbc:AwardingCriterionTypeCode[@listName='award-criterion-type'])) or (not(not(../../../cbc:ID)))">rule|text|R-Z81-MNC</assert>
        <assert id="R-MJS-M95" role="ERROR" diagnostics="ND-LotsGroupAwardCriteria_BT-543-LotsGroup" test="(not(cbc:CalculationExpression)) or (not((cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric) or (cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']/efbc:ParameterNumeric) or (cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']/efbc:ParameterNumeric)))">rule|text|R-MJS-M95</assert>
        <assert id="R-VMV-NJN" role="ERROR" diagnostics="ND-LotsGroupAwardCriteria_BT-733-LotsGroup" test="(not(cbc:Description)) or (not(not(some $x in cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterCode/normalize-space(text()) satisfies $x = 'ord-imp')))">rule|text|R-VMV-NJN</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion">
        <assert id="R-LW2-H18" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-540-LotsGroup" test="(not(cbc:Description)) or (not(not(cbc:AwardingCriterionTypeCode[@listName='award-criterion-type'])))">rule|text|R-LW2-H18</assert>
        <assert id="R-DL5-H9U" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-540-LotsGroup" test="(cbc:Description) or (not(not(not(cbc:AwardingCriterionTypeCode[@listName='award-criterion-type']))))">rule|text|R-DL5-H9U</assert>
        <assert id="R-WN9-SRE" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-541-LotsGroup-FixedNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-WN9-SRE</assert>
        <assert id="R-9DX-J5V" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-541-LotsGroup-ThresholdNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-9DX-J5V</assert>
        <assert id="R-Q3P-BC1" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-541-LotsGroup-WeightNumber" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']/efbc:ParameterNumeric)) or (not((not(cbc:Description)) or (../cbc:CalculationExpression)))">rule|text|R-Q3P-BC1</assert>
        <assert id="R-2GJ-U0Q" role="ERROR" diagnostics="ND-LotsGroupAwardCriterion_BT-734-LotsGroup" test="(not(cbc:Name)) or (not(not(cbc:Description)))">rule|text|R-2GJ-U0Q</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-fixed']">
        <assert id="R-SVV-EQL" role="ERROR" diagnostics="ND-LotsGroupAwardFixedCriterionParameter_BT-5422-LotsGroup" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-SVV-EQL</assert>
        <assert id="R-1QD-1V5" role="ERROR" diagnostics="ND-LotsGroupAwardFixedCriterionParameter_BT-5422-LotsGroup" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-1QD-1V5</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-threshold']">
        <assert id="R-MOP-U3Z" role="ERROR" diagnostics="ND-LotsGroupAwardThresholdCriterionParameter_BT-5423-LotsGroup" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-MOP-U3Z</assert>
        <assert id="R-NBA-6XZ" role="ERROR" diagnostics="ND-LotsGroupAwardThresholdCriterionParameter_BT-5423-LotsGroup" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-NBA-6XZ</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter[efbc:ParameterCode/@listName='number-weight']">
        <assert id="R-EWS-OG9" role="ERROR" diagnostics="ND-LotsGroupAwardWeightCriterionParameter_BT-5421-LotsGroup" test="(not(efbc:ParameterCode)) or (not(not(efbc:ParameterNumeric)))">rule|text|R-EWS-OG9</assert>
        <assert id="R-9P2-FSN" role="ERROR" diagnostics="ND-LotsGroupAwardWeightCriterionParameter_BT-5421-LotsGroup" test="(efbc:ParameterCode) or (not(not(not(efbc:ParameterNumeric))))">rule|text|R-9P2-FSN</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='LotsGroup']/cac:ProcurementProject">
        <assert id="R-XAF-J9C" role="ERROR" diagnostics="ND-LotsGroupProcurementScope_BT-21-LotsGroup" test="(not(cbc:Name)) or (not(not(../cbc:ID)))">rule|text|R-XAF-J9C</assert>
        <assert id="R-6RE-JZE" role="ERROR" diagnostics="ND-LotsGroupProcurementScope_BT-22-LotsGroup" test="(not(cbc:ID)) or (not(not(../cbc:ID)))">rule|text|R-6RE-JZE</assert>
        <assert id="R-PVI-8SW" role="ERROR" diagnostics="ND-LotsGroupProcurementScope_BT-24-LotsGroup" test="(not(cbc:Description)) or (not(not(../cbc:ID)))">rule|text|R-PVI-8SW</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult">
        <assert id="R-35C-UQS" role="ERROR" diagnostics="ND-NoticeResult_BT-161-NoticeResult" test="(not(cbc:TotalAmount)) or (not((some $x in efac:LotResult/efac:TenderLot/cbc:ID/normalize-space(text()) satisfies $x = ../../../../../cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cbc:ID[../cac:TenderingProcess/cac:ContractingSystem[cbc:ContractingSystemTypeCode/@listName='framework-agreement']/cbc:ContractingSystemTypeCode/normalize-space(text()) = ('fa-mix','fa-w-rc','fa-wo-rc')]/normalize-space(text())) and not(some $x in efac:SettledContract/efbc:ContractFrameworkIndicator satisfies $x = true())))">rule|text|R-35C-UQS</assert>
        <assert id="R-EQY-7NF" role="ERROR" diagnostics="ND-NoticeResult_OPT-210-Tenderer" test="(not(efac:TenderingParty/cbc:ID)) or (not(not(efac:LotTender/efac:TenderingParty/cbc:ID)))">rule|text|R-EQY-7NF</assert>
        <assert id="R-6O6-ZQ2" role="ERROR" diagnostics="ND-NoticeResult_OPT-210-Tenderer" test="(efac:TenderingParty/cbc:ID) or (not(not(not(efac:LotTender/efac:TenderingParty/cbc:ID))))">rule|text|R-6O6-ZQ2</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:ContractExtension">
        <assert id="R-1M3-VKP" role="ERROR" diagnostics="ND-OptionsAndRenewals_BT-57-Lot" test="(not(cac:Renewal/cac:Period/cbc:Description)) or (not(not(cbc:MaximumNumberNumeric/number() &gt; 0)))">rule|text|R-1M3-VKP</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization">
        <assert id="R-MGI-GKJ" role="ERROR" diagnostics="ND-Organization_BT-633-Organization" test="(not(efbc:NaturalPersonIndicator)) or (not(not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = /*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text())) and not(((efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:TenderingParty/efac:SubContractor/cbc:ID/normalize-space(text())) or (efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:TenderingParty/efac:Tenderer/cbc:ID/normalize-space(text()))) and (not(efbc:ListedOnRegulatedMarketIndicator = true())))))">rule|text|R-MGI-GKJ</assert>
        <assert id="R-35B-HO0" role="ERROR" diagnostics="ND-Organization_BT-746-Organization" test="(not(efbc:ListedOnRegulatedMarketIndicator)) or (not(not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../efac:NoticeResult/efac:TenderingParty/efac:Tenderer/cbc:ID/normalize-space(text())) and not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../efac:NoticeResult/efac:TenderingParty/efac:SubContractor/cbc:ID/normalize-space(text()))))">rule|text|R-35B-HO0</assert>
        <assert id="R-T96-GZP" role="ERROR" diagnostics="ND-Organization_OPP-050-Organization" test="(not(efbc:GroupLeadIndicator)) or (not(not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text())) or (count(../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text())) &lt; 2)))">rule|text|R-T96-GZP</assert>
        <assert id="R-53R-6MC" role="ERROR" diagnostics="ND-Organization_OPP-050-Organization" test="(efbc:GroupLeadIndicator) or (not(not(not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text())) or (count(../../../../../../cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID/normalize-space(text())) &lt; 2))))">rule|text|R-53R-6MC</assert>
        <assert id="R-5OY-W8A" role="ERROR" diagnostics="ND-Organization_OPT-302-Organization" test="(not(efac:UltimateBeneficialOwner/cbc:ID)) or (not((not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../efac:NoticeResult/efac:TenderingParty/efac:Tenderer/cbc:ID/normalize-space(text())) and not(efac:Company/cac:PartyIdentification/cbc:ID/normalize-space(text()) = ../../efac:NoticeResult/efac:TenderingParty/efac:SubContractor/cbc:ID/normalize-space(text()))) or (efbc:NaturalPersonIndicator = true()) or (efbc:ListedOnRegulatedMarketIndicator = true())))">rule|text|R-5OY-W8A</assert>
    </rule>
    <rule context="/*/cac:ProcurementProject/cac:AdditionalCommodityClassification">
        <assert id="R-DKC-DB2" role="ERROR" diagnostics="ND-ProcedureAdditionalCommodityClassification_BT-26_a_-Procedure" test="(not(cbc:ItemClassificationCode/@listName)) or (not(not(cbc:ItemClassificationCode)))">rule|text|R-DKC-DB2</assert>
        <assert id="R-7VA-45V" role="ERROR" diagnostics="ND-ProcedureAdditionalCommodityClassification_BT-26_a_-Procedure" test="(cbc:ItemClassificationCode/@listName) or (not(not(not(cbc:ItemClassificationCode))))">rule|text|R-7VA-45V</assert>
    </rule>
    <rule context="/*/cac:ProcurementProject/cac:MainCommodityClassification">
        <assert id="R-77Q-74K" role="ERROR" diagnostics="ND-ProcedureMainClassification_BT-26_m_-Procedure" test="(not(cbc:ItemClassificationCode/@listName)) or (not(not(cbc:ItemClassificationCode)))">rule|text|R-77Q-74K</assert>
        <assert id="R-HLV-NX6" role="ERROR" diagnostics="ND-ProcedureMainClassification_BT-26_m_-Procedure" test="(cbc:ItemClassificationCode/@listName) or (not(not(not(cbc:ItemClassificationCode))))">rule|text|R-HLV-NX6</assert>
    </rule>
    <rule context="/*/cac:ProcurementProject/cac:RealizedLocation/cac:Address">
        <assert id="R-8O3-GKH" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5071-Procedure" test="(not(cbc:CountrySubentityCode)) or (not(cbc:Region or not(cac:Country/cbc:IdentificationCode)))">rule|text|R-8O3-GKH</assert>
        <assert id="R-9HD-DIN" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5101_a_-Procedure" test="(not(cbc:StreetName)) or (not(not(cbc:CityName)))">rule|text|R-9HD-DIN</assert>
        <assert id="R-CHP-9T7" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5101_b_-Procedure" test="(not(cbc:AdditionalStreetName)) or (not(not(cbc:StreetName)))">rule|text|R-CHP-9T7</assert>
        <assert id="R-7ZZ-T7Z" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5101_c_-Procedure" test="(not(cac:AddressLine/cbc:Line)) or (not(not(cbc:AdditionalStreetName)))">rule|text|R-7ZZ-T7Z</assert>
        <assert id="R-VWQ-LUU" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5121-Procedure" test="(not(cbc:PostalZone)) or (not(not(cbc:CityName)))">rule|text|R-VWQ-LUU</assert>
        <assert id="R-DSD-XYA" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5121-Procedure" test="(cbc:PostalZone) or (not(cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('AFG','ALA','ALB','AND','ARG','ARM','AUS','AUT','AZE','BEL','BGD','BGR','BHR','BIH','BLM','BLR','BMU','BRA','BRB','BRN','BTN','CAN','CHE','CHL','CHN','COL','CPT','CPV','CRI','CUB','CYM','CYP','CZE','DEU','DJI','DNK','DOM','DZA','ECU','EGY','ESP','EST','ETH','FIN','FRA','FRO','FSM','GBR','GEO','GGY','GIN','GNB','GRC','GRL','GTM','GUM','HND','HRV','HTI','HUN','IDN','IMN','IND','IRL','IRN','IRQ','ISL','ISR','ITA','JEY','JOR','JPN','KAZ','KEN','KGZ','KHM','KIR','KOR','KWT','LAO','LBN','LIE','LKA','LSO','LTU','LUX','LVA','MAF','MAR','MCO','MDA','MDG','MDV','MEX','MHL','MLT','MMR','MNE','MNG','MOZ','MSR','MUS','MWI','MYS','NAM','NCL','NER','NGA','NIC','NLD','NOR','NPL','NRU','NZL','OMN','PAK','PER','PHL','PNG','POL','PRI','PRT','PRY','PSE','PYF','ROU','RUS','SAU','SDN','SEN','SGP','SJM','SLV','SMR','SPM','SRB','SVK','SVN','SWE','SWZ','THA','TJK','TKM','TLS','TTO','TUN','TUR','UKR','URY','USA','UZB','VCT','VEN','VGB','VIR','VNM','WLF','ZAF') and cbc:StreetName))">rule|text|R-DSD-XYA</assert>
        <assert id="R-K3Q-CO1" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-5131-Procedure" test="(not(cbc:CityName)) or (not(cbc:Region or not(cac:Country/cbc:IdentificationCode)))">rule|text|R-K3Q-CO1</assert>
        <assert id="R-I6Q-2VO" role="ERROR" diagnostics="ND-ProcedurePlacePerformance_BT-727-Procedure" test="(not(cbc:Region)) or (not(cbc:CountrySubentityCode))">rule|text|R-I6Q-2VO</assert>
    </rule>
    <rule context="/*/cac:ProcurementProject/cac:RealizedLocation">
        <assert id="R-CP6-E6O" role="ERROR" diagnostics="ND-ProcedurePlacePerformanceAdditionalInformation_BT-728-Procedure" test="(not(cbc:Description)) or (not(not(cac:Address/cbc:Region) and not(cac:Address/cac:Country/cbc:IdentificationCode)))">rule|text|R-CP6-E6O</assert>
        <assert id="R-1PD-ARZ" role="ERROR" diagnostics="ND-ProcedurePlacePerformanceAdditionalInformation_BT-728-Procedure" test="(cbc:Description) or (not((not(cac:Address/cbc:Region)) and (not(cac:Address/cbc:CountrySubentityCode)) and (not(cac:Address/cbc:CityName))))">rule|text|R-1PD-ARZ</assert>
    </rule>
    <rule context="/*/cac:ProcurementProject">
        <assert id="R-NE3-BFZ" role="ERROR" diagnostics="ND-ProcedureProcurementScope_BT-531-Procedure" test="(not(cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='contract-nature']/cbc:ProcurementTypeCode)) or (not(not(cbc:ProcurementTypeCode)))">rule|text|R-NE3-BFZ</assert>
    </rule>
    <rule context="/*/cac:TenderingProcess">
        <assert id="R-LW4-36W" role="ERROR" diagnostics="ND-ProcedureTenderingProcess_BT-136-Procedure" test="(not(cac:ProcessJustification[cbc:ProcessReasonCode/@listName='direct-award-justification']/cbc:ProcessReasonCode)) or (not(not(cbc:ProcedureCode/normalize-space(text()) = 'neg-wo-call')))">rule|text|R-LW4-36W</assert>
    </rule>
    <rule context="/*">
        <assert id="R-B5U-DBG" role="ERROR" diagnostics="ND-Root_BT-136-Procedure" test="(cac:TenderingProcess/cac:ProcessJustification[cbc:ProcessReasonCode/@listName='direct-award-justification']/cbc:ProcessReasonCode) or (not(cac:TenderingProcess/cbc:ProcedureCode/normalize-space(text()) = 'neg-wo-call'))">rule|text|R-B5U-DBG</assert>
        <assert id="R-EBR-R75" role="ERROR" diagnostics="ND-Root_BT-196-notice" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureJustification/efbc:NondisclosureJustificationDescription)) or (not(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureJustification/efbc:NondisclosureJustificationCode)))">rule|text|R-EBR-R75</assert>
        <assert id="R-J7T-D1R" role="ERROR" diagnostics="ND-Root_BT-197-notice" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureJustification/efbc:NondisclosureJustificationCode)) or (not(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureReference/efbc:NondisclosureID)))">rule|text|R-J7T-D1R</assert>
        <assert id="R-KSK-7VV" role="ERROR" diagnostics="ND-Root_BT-197-notice" test="(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureJustification/efbc:NondisclosureJustificationCode) or (not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureReference/efbc:NondisclosureID))">rule|text|R-KSK-7VV</assert>
        <assert id="R-4KI-XSJ" role="ERROR" diagnostics="ND-Root_BT-198-notice" test="(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efbc:InformationDisclosureDate)) or (not(not(ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeInformationNondisclosure/efac:NondisclosureReference/efbc:NondisclosureID)))">rule|text|R-4KI-XSJ</assert>
    </rule>
    <rule context="/*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty">
        <assert id="R-TVJ-963" role="ERROR" diagnostics="ND-ServiceProviderParty_OPT-030-Procedure-SProvider" test="(not(cbc:ServiceTypeCode)) or (not(not(cac:Party/cac:PartyIdentification/cbc:ID)))">rule|text|R-TVJ-963</assert>
        <assert id="R-PL0-I58" role="ERROR" diagnostics="ND-ServiceProviderParty_OPT-030-Procedure-SProvider" test="(cbc:ServiceTypeCode) or (not(not(not(cac:Party/cac:PartyIdentification/cbc:ID))))">rule|text|R-PL0-I58</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:SettledContract">
        <assert id="R-M0Y-T7P" role="ERROR" diagnostics="ND-SettledContract_BT-1451-Contract" test="(not(cbc:AwardDate)) or (not((not(cbc:ID))))">rule|text|R-M0Y-T7P</assert>
        <assert id="R-J00-IVK" role="ERROR" diagnostics="ND-SettledContract_BT-3202-Contract" test="(not(efac:LotTender/cbc:ID)) or (not((not(cbc:ID)) or (not(../efac:LotTender/cbc:ID))))">rule|text|R-J00-IVK</assert>
        <assert id="R-UUE-QAP" role="ERROR" diagnostics="ND-SettledContract_BT-3202-Contract" test="(efac:LotTender/cbc:ID) or (not(not((not(cbc:ID)) or (not(../efac:LotTender/cbc:ID)))))">rule|text|R-UUE-QAP</assert>
        <assert id="R-QAC-HF0" role="ERROR" diagnostics="ND-SettledContract_BT-721-Contract" test="(not(cbc:Title)) or (not(not(efac:LotTender/cbc:ID)))">rule|text|R-QAC-HF0</assert>
    </rule>
    <rule context="/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='strategic-procurement']">
        <assert id="R-L43-B6L" role="ERROR" diagnostics="ND-StrategicProcurementType_BT-777-Lot" test="(not(cbc:ProcurementType)) or (not(not(cbc:ProcurementTypeCode) or cbc:ProcurementTypeCode/normalize-space(text()) = 'none'))">rule|text|R-L43-B6L</assert>
        <assert id="R-MCY-TNL" role="ERROR" diagnostics="ND-StrategicProcurementType_BT-777-Lot" test="(cbc:ProcurementType) or (not(not(not(cbc:ProcurementTypeCode) or cbc:ProcurementTypeCode/normalize-space(text()) = 'none')))">rule|text|R-MCY-TNL</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:TenderingParty/efac:SubContractor">
        <assert id="R-FT5-2FZ" role="ERROR" diagnostics="ND-SubContractor_OPT-301-Tenderer-MainCont" test="(not(efac:MainContractor/cbc:ID)) or (not(not(cbc:ID)))">rule|text|R-FT5-2FZ</assert>
        <assert id="R-DTE-5HX" role="ERROR" diagnostics="ND-SubContractor_OPT-301-Tenderer-MainCont" test="(efac:MainContractor/cbc:ID) or (not(not(not(cbc:ID))))">rule|text|R-DTE-5HX</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender/efac:SubcontractingTerm[efbc:TermCode/@listName='applicability']">
        <assert id="R-SD4-1DN" role="ERROR" diagnostics="ND-SubcontractedContract_BT-553-Tender" test="(not(efbc:TermAmount)) or (not(not(efbc:ValueKnownIndicator = true())))">rule|text|R-SD4-1DN</assert>
        <assert id="R-PJC-0O5" role="ERROR" diagnostics="ND-SubcontractedContract_BT-553-Tender" test="(efbc:TermAmount) or (not(efbc:ValueKnownIndicator = true()))">rule|text|R-PJC-0O5</assert>
        <assert id="R-BOK-HY8" role="ERROR" diagnostics="ND-SubcontractedContract_BT-554-Tender" test="(not(efbc:TermDescription)) or (not(not(efbc:TermCode/normalize-space(text()) = 'yes')))">rule|text|R-BOK-HY8</assert>
        <assert id="R-AGO-EU7" role="ERROR" diagnostics="ND-SubcontractedContract_BT-555-Tender" test="(not(efbc:TermPercent)) or (not(not(efbc:PercentageKnownIndicator = true())))">rule|text|R-AGO-EU7</assert>
        <assert id="R-1MH-7UF" role="ERROR" diagnostics="ND-SubcontractedContract_BT-555-Tender" test="(efbc:TermPercent) or (not(efbc:PercentageKnownIndicator = true()))">rule|text|R-1MH-7UF</assert>
        <assert id="R-4LK-7KO" role="ERROR" diagnostics="ND-SubcontractedContract_BT-730-Tender" test="(not(efbc:ValueKnownIndicator)) or (not(not(efbc:TermCode/normalize-space(text()) = 'yes')))">rule|text|R-4LK-7KO</assert>
        <assert id="R-Q0G-V36" role="ERROR" diagnostics="ND-SubcontractedContract_BT-730-Tender" test="(efbc:ValueKnownIndicator) or (not(efbc:TermCode/normalize-space(text()) = 'yes'))">rule|text|R-Q0G-V36</assert>
        <assert id="R-LLU-1VL" role="ERROR" diagnostics="ND-SubcontractedContract_BT-731-Tender" test="(not(efbc:PercentageKnownIndicator)) or (not(not(efbc:TermCode/normalize-space(text()) = 'yes')))">rule|text|R-LLU-1VL</assert>
        <assert id="R-LUX-669" role="ERROR" diagnostics="ND-SubcontractedContract_BT-731-Tender" test="(efbc:PercentageKnownIndicator) or (not(efbc:TermCode/normalize-space(text()) = 'yes'))">rule|text|R-LUX-669</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:TenderingParty/efac:Tenderer">
        <assert id="R-NTL-4SB" role="ERROR" diagnostics="ND-Tenderer_OPT-170-Tenderer" test="(not(efbc:GroupLeadIndicator)) or (not(../cbc:ID[count(../efac:Tenderer/cbc:ID/normalize-space(text())) &lt; 2]))">rule|text|R-NTL-4SB</assert>
        <assert id="R-XYJ-1C9" role="ERROR" diagnostics="ND-Tenderer_OPT-170-Tenderer" test="(efbc:GroupLeadIndicator) or (not(not(../cbc:ID[count(../efac:Tenderer/cbc:ID/normalize-space(text())) &lt; 2])))">rule|text|R-XYJ-1C9</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:TenderingParty">
        <assert id="R-L44-N8V" role="ERROR" diagnostics="ND-TenderingParty_OPT-300-Tenderer" test="(not(efac:Tenderer/cbc:ID)) or (not(not(../efac:LotTender/cbc:ID)))">rule|text|R-L44-N8V</assert>
        <assert id="R-1NS-LLY" role="ERROR" diagnostics="ND-TenderingParty_OPT-300-Tenderer" test="(efac:Tenderer/cbc:ID) or (not(not(not(../efac:LotTender/cbc:ID))))">rule|text|R-1NS-LLY</assert>
        <assert id="R-5Y6-44Y" role="ERROR" diagnostics="ND-TenderingParty_OPT-301-Tenderer-SubCont" test="(not(efac:SubContractor/cbc:ID)) or (not(not(efac:Tenderer/cbc:ID)))">rule|text|R-5Y6-44Y</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:TouchPoint">
        <assert id="R-81F-UH6" role="ERROR" diagnostics="ND-Touchpoint_BT-16-Organization-TouchPoint" test="(not(cac:PostalAddress/cbc:Department)) or (not(not(cac:PartyName/cbc:Name)))">rule|text|R-81F-UH6</assert>
        <assert id="R-OMA-6QL" role="ERROR" diagnostics="ND-Touchpoint_BT-507-Organization-TouchPoint" test="(not(cac:PostalAddress/cbc:CountrySubentityCode)) or (not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('ALB','AUT','BEL','BGR','CHE','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ISL','ITA','LIE','LTU','LUX','LVA','MKD','MLT','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE','TUR','UKR','XKX'))))">rule|text|R-OMA-6QL</assert>
        <assert id="R-M1R-PVG" role="ERROR" diagnostics="ND-Touchpoint_BT-507-Organization-TouchPoint" test="(cac:PostalAddress/cbc:CountrySubentityCode) or (not(not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('ALB','AUT','BEL','BGR','CHE','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ISL','ITA','LIE','LTU','LUX','LVA','MKD','MLT','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE','TUR','UKR','XKX')))))">rule|text|R-M1R-PVG</assert>
        <assert id="R-DTG-235" role="ERROR" diagnostics="ND-Touchpoint_BT-510_a_-Organization-TouchPoint" test="(not(cac:PostalAddress/cbc:StreetName)) or (not(not(cac:PostalAddress/cbc:CityName)))">rule|text|R-DTG-235</assert>
        <assert id="R-3JA-HHL" role="ERROR" diagnostics="ND-Touchpoint_BT-510_b_-Organization-TouchPoint" test="(not(cac:PostalAddress/cbc:AdditionalStreetName)) or (not(not(cac:PostalAddress/cbc:StreetName)))">rule|text|R-3JA-HHL</assert>
        <assert id="R-ETI-PYM" role="ERROR" diagnostics="ND-Touchpoint_BT-510_c_-Organization-TouchPoint" test="(not(cac:PostalAddress/cac:AddressLine/cbc:Line)) or (not(not(cac:PostalAddress/cbc:AdditionalStreetName)))">rule|text|R-ETI-PYM</assert>
        <assert id="R-SAY-IDR" role="ERROR" diagnostics="ND-Touchpoint_BT-512-Organization-TouchPoint" test="(cac:PostalAddress/cbc:PostalZone) or (not(cac:PostalAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('AFG','ALA','ALB','AND','ARG','ARM','AUS','AUT','AZE','BEL','BGD','BGR','BHR','BIH','BLM','BLR','BMU','BRA','BRB','BRN','BTN','CAN','CHE','CHL','CHN','COL','CPT','CPV','CRI','CUB','CYM','CYP','CZE','DEU','DJI','DNK','DOM','DZA','ECU','EGY','ESP','EST','ETH','FIN','FRA','FRO','FSM','GBR','GEO','GGY','GIN','GNB','GRC','GRL','GTM','GUM','HND','HRV','HTI','HUN','IDN','IMN','IND','IRL','IRN','IRQ','ISL','ISR','ITA','JEY','JOR','JPN','KAZ','KEN','KGZ','KHM','KIR','KOR','KWT','LAO','LBN','LIE','LKA','LSO','LTU','LUX','LVA','MAF','MAR','MCO','MDA','MDG','MDV','MEX','MHL','MLT','MMR','MNE','MNG','MOZ','MSR','MUS','MWI','MYS','NAM','NCL','NER','NGA','NIC','NLD','NOR','NPL','NRU','NZL','OMN','PAK','PER','PHL','PNG','POL','PRI','PRT','PRY','PSE','PYF','ROU','RUS','SAU','SDN','SEN','SGP','SJM','SLV','SMR','SPM','SRB','SVK','SVN','SWE','SWZ','THA','TJK','TKM','TLS','TTO','TUN','TUR','UKR','URY','USA','UZB','VCT','VEN','VGB','VIR','VNM','WLF','ZAF')))">rule|text|R-SAY-IDR</assert>
        <assert id="R-2OX-PDZ" role="ERROR" diagnostics="ND-Touchpoint_BT-513-Organization-TouchPoint" test="(not(cac:PostalAddress/cbc:CityName)) or (not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode)))">rule|text|R-2OX-PDZ</assert>
        <assert id="R-QBU-VVH" role="ERROR" diagnostics="ND-Touchpoint_BT-513-Organization-TouchPoint" test="(cac:PostalAddress/cbc:CityName) or (not(not(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode))))">rule|text|R-QBU-VVH</assert>
        <assert id="R-EDA-JIW" role="ERROR" diagnostics="ND-Touchpoint_BT-514-Organization-TouchPoint" test="(not(cac:PostalAddress/cac:Country/cbc:IdentificationCode)) or (not(not(cac:PartyName/cbc:Name)))">rule|text|R-EDA-JIW</assert>
    </rule>
    <rule context="/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:UltimateBeneficialOwner">
        <assert id="R-VCB-QZ7" role="ERROR" diagnostics="ND-UBO_BT-507-UBO" test="(not(cac:ResidenceAddress/cbc:CountrySubentityCode)) or (not(not(cac:ResidenceAddress/cac:Country/cbc:IdentificationCode/normalize-space(text()) = ('ALB','AUT','BEL','BGR','CHE','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ISL','ITA','LIE','LTU','LUX','LVA','MKD','MLT','MNE','NLD','NOR','POL','PRT','ROU','SRB','SVK','SVN','SWE','TUR','UKR','XKX'))))">rule|text|R-VCB-QZ7</assert>
        <assert id="R-XR9-CCC" role="ERROR" diagnostics="ND-UBO_BT-510_a_-UBO" test="(not(cac:ResidenceAddress/cbc:StreetName)) or (not(not(cbc:FamilyName)))">rule|text|R-XR9-CCC</assert>
        <assert id="R-409-1BU" role="ERROR" diagnostics="ND-UBO_BT-510_b_-UBO" test="(not(cac:ResidenceAddress/cbc:AdditionalStreetName)) or (not(not(cac:ResidenceAddress/cbc:StreetName)))">rule|text|R-409-1BU</assert>
        <assert id="R-OBF-MMT" role="ERROR" diagnostics="ND-UBO_BT-510_c_-UBO" test="(not(cac:ResidenceAddress/cac:AddressLine/cbc:Line)) or (not(not(cac:ResidenceAddress/cbc:AdditionalStreetName)))">rule|text|R-OBF-MMT</assert>
        <assert id="R-IW0-XYH" role="ERROR" diagnostics="ND-UBO_BT-513-UBO" test="(not(cac:ResidenceAddress/cbc:CityName)) or (not(not(cbc:FamilyName)))">rule|text|R-IW0-XYH</assert>
        <assert id="R-YD5-QFT" role="ERROR" diagnostics="ND-UBO_BT-514-UBO" test="(not(cac:ResidenceAddress/cac:Country/cbc:IdentificationCode)) or (not(not(cbc:FamilyName)))">rule|text|R-YD5-QFT</assert>
    </rule>
</pattern>
