= Field metadata

== What is a field

The https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32019R1780[eForms
Regulation] defines, in table 2 of its annex, a set of business terms (BT) for
the various pieces of information that are in a notice. But the level of
granularity of those BT is not sufficient for representation of the information
in XML notice.

For example, there is a single business term, BT-27, for the estimated value of
the procurement procedure or a lot. But the estimated value of a lot is in a
different location in the XML, and will be subject to different rules than the
estimated value of the whole procedure.

To resolve those ambiguities we added the notion of fields. Each field is
related to one single business term, and corresponds to a more precise
definition of the information it contains. The identifier of a field always
starts with the identifier of the business term.

For the example above, the fields defined for BT-27 are:

* BT-27-Procedure : estimated value of the procedure
* BT-27-Lot : estimated value of a lot
* BT-27-Part : estimated value of part
* BT-27-LotsGroup : estimated value of a group of lots 

== The field repository

[WARNING]
====
The structure and content of the field repository described below are driven by
the specific needs of our various applications.

As we think it can be useful for others, we are sharing it publicly, and you are
welcome to make any use of it. But we currently do not guarantee the stability
of the structure or content.
====

The field repository is a JSON file that contains all relevant information for
each field we have defined, in a structured and reusable form.

We are using this file to provide the definition of all fields to our
form-filling application (eNotices). Each form is then made of a specific subset
of those fields.

The field repository is mainly a list of fields, preceded by some version information:

[source,json]
----
{
  "version": "1", // <1>
  "ublVersion": "2.3", // <2>
  "xsdVersion": "eForms-0.3.0", // <3>
  "metadataDatabase": { // <4>
    "version": "0.0.4",
    "createdOn": "2021-08-20T16:46:39"
  },
  "fields": [ // <5>
    { ... },
	...
  ]
}
----
<1> TODO
<2> version of the UBL standard used
<3> TODO
<4> version number and date of data used to create this file
<5> list of fields

== Field information

For each field, various characteristics of the field are indicated.

[source,json]
----
    {
      "id": "BT-01-notice", // <1>
      "name": "Procedure Legal Basis", // <2>
      "btId": "BT-01", // <3>
      "xpath": "/*/cbc:RegulatoryDomain", // <4>
      "type": "internal-code", // <5>
      "legalType": "CODE", // <6>
      "description": "", // <7>
      "repeatable": false, // <8>
      "codeList": "legal-basis" // <9>
	  ...
    }
----
<1> Identifier of the field.
<2> Short name of the field.
<3> Identifier of the business term to which the field corresponds.
<4> Location of the field in an XML notice, as an XPath.
<5> Technical data type of the field.
<6> Data type of the business term, as indicated in the eForms Regulation.
<7> Description of the field (currently not used).
<8> Indicates if the field can appear more than once inside its container
<9> Identifier of the code list from which the field takes its values.
Applicable only for fields of type "code" or "internal-code"

=== Field data types

The possible data type for a field are:

* `id` : string representing an identifier
* `id-ref` : string representing a reference to an identifier
* `indicator` : boolean (true or false)
* `integer`
* `number` : TODO
* `amount` : monetary amount, comprised of a numerical value and a currency
* `measure` : numerical value associated with a measurement unit
* `code` : string representing concept in a code list
* `internal-code` : string representing concept in a code list
* `zoned-date` : date with timezone
* `zoned-time` : time with timezone
* `email` : string representing a e-mail address
* `phone` : string representing a phone number
* `url` : string representing an URL
* `text` : language independent string
* `text-multilingual` : string that can be translated in multiple languages

=== Field constraints

TODO

