:xrefstyle: short

= Notice information

The elements at the upper most level of the XML instance of a notice,
concern the information listed in <<noticeRelatedInformationTable>>. This table contains the
Business Terms, a shortened description, its cardinality and the XML
components used to mark the information. The specified cardinality is
more restrictive than the one in the schema; it is used to express
requirements stated in https://ec.europa.eu/docsroom/documents/38172[the
Regulation annex].

[[noticeRelatedInformationTable]]
.Notice related information
[cols=".^25%h,^.^20%,^.^15%,.^40%",options="header",]
|===
^h|*eForms BT* h|*Details* h|*Card.* ^h|*XSD element*
h|_Notice SubType (OPP-070)_ a| xref:subtypeSection[xrefstyle=short] |*1*
|efac:NoticeSubType/cbc:SubTypeCode

|_Notice Publication ID (OPP-010)_ | xref:pubInfoSection[xrefstyle=short] |*?*
|efac:Publication/efbc:NoticePublicationID[@schemeName='ojs-notice-id']

|_OJEU Identifier (OPP-011)_ | xref:pubInfoSection[xrefstyle=short] |*?*
|efac:Publication/efbc:GazetteID[@schemeName='ojs-id']

|_OJEU Publication Date (OPP-012)_ | xref:pubInfoSection[xrefstyle=short] |*?*
|efac:Publication/efbc:PublicationDate

|_UBL version ID (UBL)_ | xref:pubInfoSection[xrefstyle=short] |*1* |cbc:UBLVersionID

|_Customization ID (UBL)_ | xref:customIDSection[xrefstyle=short] |*1* |cbc:CustomizationID

|Notice Identifier (BT-701) | xref:noticeIDSection[xrefstyle=short] |*1* |cbc:ID

|Procedure Identifier (BT-04) |xref:procedureIDSection[xrefstyle=short] |*0..1* |cbc:ContractFolderID

|Notice Dispatch Date (BT-05) |xref:dispatchDateSection[xrefstyle=short] |*1* a|
cbc:IssueDate

cbc:IssueTime

|Notice Version (BT-757) |xref:noticeIDSection[xrefstyle=short] |*1* |cbc:VersionID

|Notice Publication Date Preferred (BT-738) | xref:preferredDateSection[xrefstyle=short] |*0..1*
|cbc:RequestedPublicationDate

|Future Notice (BT-127) | xref:futureNoticeSection[xrefstyle=short] |*0..1* |cbc:PlannedDate

|Procedure Legal Basis (BT-01) | xref:legalBasisSection[xrefstyle=short] |*1* |cbc:RegulatoryDomain

|Form Type (BT-03) | xref:subtypeSection[xrefstyle=short] |*1* |cbc:NoticeTypeCode/@listName

|Notice Type (BT-02) | xref:subtypeSection[xrefstyle=short] |*1* |cbc:NoticeTypeCode

|Notice Official Language (BT-702) | xref:noticeLanguageSection[xrefstyle=short] |*1..n* a|
cbc:NoticeLanguageCode

cac:AdditionalNoticeLanguage/cbc:ID

ah|
Organization

_(Buyer, CPB, Service Provider ...)_

|  xref:organizationsSection[xrefstyle=short] |*1..n* |cac:ContractingParty and child elements
|===

[[pubInfoSection]]
== Notice Publication information

The Notice Publication information (Date, OJEU and OJS Notice IDs) shall be marked the following way:

[source, xml]
----
    <efac:Publication>
        <efbc:NoticePublicationID schemeName="ojs-notice-id">12345678-2023</efbc:NoticePublicationID>
        <efbc:GazetteID schemeName="ojs-id">123/2023</efbc:GazetteID>
        <efbc:PublicationDate>2023-03-14+01:00</efbc:PublicationDate>
   </efac:Publication>
----

[[UBLversionSection]]
== UBL version ID

The earliest UBL 2 version containing all elements of the schema
(besides the ones from the extension) is "2.3". Unless differently
stated, this is the only expected and accepted value.

[source, xml]
----
    <cbc:UBLVersionID>2.3</cbc:UBLVersionID>
----

[[customIDSection]]
== Customization ID

This element identifies the customization used for the notice.
Identification is based on the complete set (_schemas+rules_) limited to
the major and minor version numbers (cf. <<versioningSection>>).

[source, xml]
----
    <cbc:CustomizationID>eforms-sdk-0.2</cbc:CustomizationID>
----

[[noticeIDSection]]
== Notice & Version Identifiers

The "Notice identifier" identifies a notice amongst all other existing
ones. A notice may have multiple versions and only the different
versions of a given notice shall share the notice identifier value.
Versions of a notice are purely editorial and for a given Notice ID, a
single version may be published.

The notice identifier shall follow a predefined scheme, it will be a
version 4 Universally Unique Identifier (UUID):

[source, xml]
----
    <cbc:ID schemeName="notice-id">0f56d80f-8a5f-4876-8e24-feaa766c456d</cbc:ID>
----

The version identifier of a given notice shall increase with any new
version of that notice. New versions use the same schema as the original
notice. The identifier shall be a two characters positive integer (i.e.
"00" excluded). The version "01" shall be kept for the first version of
the notice, subsequent versions shall be submitted and received in
increasing numbering order.

[source, xml]
----
    <cbc:VersionID>01</cbc:VersionID>
----

Any received valid notices shall all have a unique Notice ID
independently from the version ID

[[procedureIDSection]]
== Procedure Identifier

The Procedure Identifier allows distinguishing procurement procedures
and shall be globally unique. Specified in the notice, it identifies the
procurement procedure the notice belongs to.

Like the Notice Identifier, the Procedure Identifier shall be a version
4 UUID.

[source,xml]
----
<cbc:ContractFolderID>1e86a664-ae3c-41eb-8529-0242ac130003</cbc:ContractFolderID>
----

Performed controls ensure its uniquenessfootnote:[The first received notice within a given procedure shall either trigger the record of the corresponding procedure ID, or the generation of an error when this value is already used.] and
help check consistency amongst received notices (For a given procedure,
sequence and content of notices will be carefully checked).

This information does not exist for notices of "_Planning_" form type.

[[dispatchDateSection]]
== Notice Dispatch Date

The *+++date and time+++* of the notice receipt by OP. This date will be
added before its submission to OP and its trustworthiness evaluated
based on the actual receipt time and a range of acceptable variationsfootnote:[To be defined by Business].

Date and time shall be expressed locally with shift to Coordinated
Universal Time.

Values shall vary from 00:00:00.0000 to 24:00:00 excludedfootnote:[For disambiguity, the hour value "24" shall not be used.],
with as many decimals for the seconds as required.

A notice sent on November 26^th^, 2019 at 1:38:54 PM CET (i.e. UTC +1)
to OP shall be marked:

[source,xml]
----
<cbc:IssueDate>2019-11-26+01:00</cbc:IssueDate>
<cbc:IssueTime>13:38:54+01:00</cbc:IssueTime>
----

When referring to midnight (end of day for a given date), use 00:00:00
(start of the following day) instead and adjust the referenced day
(month, and year) accordingly.

For December 5^th^, 2020 at midnight CET, the markup shall look like:

[source,xml]
----
<cbc:IssueDate>2020-12-06+01:00</cbc:IssueDate>
<cbc:IssueTime>00:00:00+01:00</cbc:IssueTime>
----

Any date shall be specified with time zone. When a date is associated 
with a time, both must share the same shift to Coordinated Universal Time.

[[preferredDateSection]]
== Notice Publication Date Preferred

The "Notice Publication Date Preferred" is the date on which the buyer
wishes the notice to be published on the TED website. It can be used to
help the buyer respect the requirements that exist between publications
at national and European levels.

The publication request of a notice for March 15^th^, 2020 shall be
marked:

[source,xml]
----
<cbc:RequestedPublicationDate>2020-03-15+01:00</cbc:RequestedPublicationDate>
----

[[futureNoticeSection]]
== Future Notice

The "_cbc:PlannedDate_" is used for planning notices (PIN only excluded)
to specify when the competition notice will be published. Mark-up should
be as follows:

[source,xml]
----
<cbc:PlannedDate>2020-03-15+01:00</cbc:PlannedDate>
----

[[legalBasisSection]]
== Procedure Legal Basis

The Procedure Legal Basis term refers to the EU regulatory domain that
applies to the procurement.

The value is the corresponding CELEX number (e.g. "_32014L0024_" for
Directive 2014/24). Only some values of the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/legal-basis[dedicated
codelist] may be used in the context of the eProcurement. The "other"
value shall exclusively be used for below threshold notices. Further
needed Legal Basis may be specified as specified in <<crossBorderLawSection>>.

A notice for a procedure under Directive 2014/24 shall have its legal
basis information identified using:

[source,xml]
----
<cbc:RegulatoryDomain>32014L0024</cbc:RegulatoryDomain>
----

National and other local Legal Bases should be expressed as specified in
<<otherLegalBasisSection>>.

[[subtypeSection]] 
== Form and Notice Types, Notice Subtype

The information associated with these terms evolves with the procedure.
Existing codelists (i.e.
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/form-type[form-type],
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/notice-type[notice-type]
and the technical notice-subtype) specify acceptable values; these
values must also be consistent with each other (i.e. specified values
must comply with the situations as described in <<noticeTypesSubtypesTable>>).

The Notice SubType (OPP-070) shall be marked as follow:

[source,xml]
----
<efac:NoticeSubType>
    <cbc:SubTypeCode listName="notice-subtype">16</cbc:SubTypeCode>
</efac:NoticeSubType>
----

A notice of "Planning" form type and "PIN only" notice type shall have
this information marked the following way:

[source,xml]
----
<cbc:NoticeTypeCode listName="planning">pin-only</cbc:NoticeTypeCode>
----

[[noticeLanguageSection]]
== Notice Official Language

The "_Notice Official Language_" designates an _EU Official language_ in
which the notice is officially available.

Notice official languages shall be marked:

[source,xml]
----
<cbc:NoticeLanguageCode>ENG</cbc:NoticeLanguageCode>
<cac:AdditionalNoticeLanguage>
    <cbc:ID>DEU</cbc:ID>
</cac:AdditionalNoticeLanguage>
<cac:AdditionalNoticeLanguage>
    <cbc:ID>FRA</cbc:ID>
</cac:AdditionalNoticeLanguage>
----

Using:

* "_cbc:NoticeLanguageCode_" for a first official languagefootnote:[There is no specific order here and the approach is purely technical. Identification of the first linguistic version (i.e. code for NoticeLanguageCode) is based on the original version (i.e. first encoded text linguistic version) or the author's environment.], and

* "_cac:AdditionalNoticeLanguage_" for any additional official
language.

In the XML instance, the attribute "languageID" of a _text-type_
element, identifies, using a
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/language[language]
code, the language used for the text. The specification of the value for
this attribute is required for all text-type elements within a noticefootnote:[A few text-type elements (e.g. cbc:RegulatoryDomain, cbc:Region, cbc:LimitationDescription) will use codes instead and for these the languageID attribute shall not be used. They will be presented later on.].

A "_Notice non-official language_" refers to any (EU) Official Language
not considered as authentic (i.e. for which only part of the notice text
exist). The whole list of such languages may be deduced from the
specified "_languageID_" attribute values and the marked-up notice
official languages.

Non-EU languages are not to be considered for publication at EU level
and should therefore not be referenced. Each text-type element should be
used once and only once for a given language.

For a given procurement procedure, the list of official languages shall
be the same for all notices.

[[organizationsSection]]
== Organizations

Organizations informations are grouped into a dedicated element in an
extension and referred to in the rest of the XML instance as explained
in <<partiesSection>> where details on information mark-up may be found.

The "_cac:ContractingParty_" element allows for encoding of the parties
involved in the procurement procedure, like "buyer" (including
description of their role in a joint procurement), or "service provider"
(e-Sender, Procurement service provider ...).
