:xrefstyle: short
:page-toclevels: -1


= Procedure, Group of Lots, Lot & Part related information

== Introduction

Procedure related information exists at the root of the notice as shown
in <<reusedElementsFigure>> above.

Each Groups of Lots, Lot, and Part, has its information in its dedicated
"_cac:ProcurementProjectLot_" element whose identifier is built using
the appropriate scheme from <<numberingSchemesForPartsLotsAndGroupOfLotsTable>>. These technical identifiers are
unique within a notice and may not evolve (i.e. the same Lot will have
the same technical identifier from the start to the end of the
procurement procedure).

[[numberingSchemesForPartsLotsAndGroupOfLotsTable]]
.Numbering schemes for Parts, Lots and Group of Lots
[cols="^.^20%,^.^20%,^.^20%,<.^40%",]
|===
|*Object* |*Scheme Name* |*Scheme* ^|*Comment*

|*Group of Lots* |LotsGroup |GLO-XXXX .3+a|
XXXX: set of 4 digits.

By default the numbering should be increased by 1 from one object to the
following object of the same category and leading 0 should be used to
satisfy the 4 digits format

For Procedure without Lots (i.e. with a single "technical" lot), the ID
shall be LOT-0000.

|*Lot* |Lot |LOT-XXXX

|*Part* |Part |PAR-XXXX
|===

As Procedures without lots (and PIN without parts) are to be treated
technically as a procedure with exactly one lot (or part), there shall
always be at least one "_cac:ProcurementProjectLot_" element. This
approach will simplify the processing for all notices by differentiating
high level description purpose (i.e. procurement procedure purpose - §
II.1 of former forms) from the more specific ones (i.e. Lot specific
purpose - § II.2 of former forms)

The extract below illustrates, for a Group of Lots and two Lots, the way
the schemes are used to identify the objects whose information (not
reported here for readability purpose) is specified.

[source,xml]
----
<cac:ProcurementProjectLot>
    <cbc:ID schemeName="LotsGroup">GLO-0001</cbc:ID>
    <!-- Interrupted Mark-Up -->
    <!-- Information about Group of Lots 1 -->
</cac:ProcurementProjectLot>
<cac:ProcurementProjectLot>
    <cbc:ID schemeName="Lot">LOT-0001</cbc:ID>
    <!-- Interrupted Mark-Up -->
    <!-- Information about Lot 1 -->
</cac:ProcurementProjectLot>
<cac:ProcurementProjectLot>
    <cbc:ID schemeName="Lot">LOT-0002</cbc:ID>
    <!-- Interrupted Mark-Up -->
    <!-- Information about Lot 2 -->
</cac:ProcurementProjectLot>
----

Regarding Group of Lots:

* The Buyer defines Groups of Lots at the start of the whole
Procurement Procedure;

* Groups shall not coexist with Partsfootnote:[Parts may only exist in "PIN Only" notices. Lots and Parts may not coexist and Group of lots may only coexist with Lots.];

* They shall not contain less than two Lots;

* The group composition (i.e. the exhaustive list of Lots a
group contains) is specified in the Tendering Terms at root level using
sub-elements of "_cac:LotDistribution_" as described in <<maxLotsSection>>;

* Other information about a Group of Lots is located separately
from its composition, under a dedicated "_cac:ProcurementProjectLot_"
element;

* With information already specified at Lots level, fewer data
are needed for Group of Lots.

== Information relative to each object

As illustrated in <<reusedElementsFigure>>, each object ("_Procedure_", "_Group of
Lots_", "_Lot_" and "_Part_") has its information encoded in 3 main
blocks: "_TenderingTerms_", "_TenderingProcess_" and
"_ProcurementProject_".

The following tables highlight, for each of them, the main information
covered by each block. This information is purely indicative as the
content evolves according to the stages (e.g. some information relevant
for a contract notice may become irrelevant for a contract award notice,
while other information is only known after awarding a Lot).

[[majorBlocksOfProcurementProcedureRelatedInformationTable]]
.Major blocks of Procurement Procedure related information
[cols=".^30%,<.^70%",options="header",]
|===
^|*Block* ^|*Topics*
|*Tendering Terms* a|
* Applicable cross border legislation

* Lots distribution information (Maximum number of tendered &
awarded Lots per tenderer, Definition of Groups of Lots)

|*Tendering Process* a|
* Procedure Type & Description

* Whether tenders shall apply to all the Lots

|*Procurement Project* a|
* Procurement Project Internal identifier (+++*+++)

* Procurement Project Title & Description

* Main & additional natures

* Notice aggregated values

* Quantity & value

* Framework related information

* Classification (CPV)

* Planned period, extensions (options & renewals)

2+|(+++*+++) Internal Identifier assigned by the Contracting Authority. It is not required to be globally unique

|===






[[majorBlocksOfGroupOfLotsRelatedInformationTable]]
.Major blocks of Group of Lots related information
[cols=".^30%,<.^70%",options="header",]
|===
^|*Block* ^|*Topics*
|*Tendering Terms* a|* Awarding criteria (Group specific)

|*Tendering Process* a|
* Groups related statistics (CAN)

* Estimation, at the start of the Procurement Procedure, of the
Group Framework Agreement Maximal value)

* Group associated Maximal Framework Agreement value (ceiling
value specified in the contract)

|*Procurement Project* a|
* Internal ID, Title & Description

* Aggregated values (e.g. in A CAN, sum of individual Framework
Agreements for Lots belonging to the group).

|===

[[majorBlocksOfLotRelatedInformationTable]]
.Major blocks of Lot related information
[cols=".^30%,<.^70%",options="header",]
|===
^|*Block* ^|*Topics*

|*Tendering Terms* a|
* Selection & Awarding criteria (Lot specific)

* Tendering, Execution & Tenderer requirements

* Parties involved from information provision to tenders
evaluation

|*Tendering Process* a|
* Lots related statistics (CAN)

* Initial estimates and information on Framework Agreement

* Reference to planning notices used for the procedure

* Required tools and exchange formats

* Procedure key milestones

* Limitations & candidates shortlists

|*Procurement Project* a|
* Internal ID, Title & Description

* Contract nature and type

* Strategic project type and statistics

* Accessibility criteria

* Place of performance

* Planned period & contract extensions

* Subcontract conditions

* Concessions revenues.

|===

[[majorBlocksOfPartRelatedInformationTable]]
.Major blocks of Part related information
[cols=".^30%,<.^70%",options="header",]
|===
^|*Block* ^|*Topics*
|*Tendering Terms* |* Tenderer and execution requirements.
|*Tendering Process* a|
* Framework agreement,

* Tools & access to documentation.

|*Procurement Project* a|
* Contract nature & type

* Title & description

* Planned period

* Place of performance.

|===

[[tenderingTermsSection]]
== Tendering terms

Tendering terms group information as diverse as EU funding, exclusion
grounds, reserved participation/execution.

<<tenderingTermsRelatedInformationTable>> lists, in their order of appearance in the XML, each of the
eForms Business Terms that have a corresponding component in the
"_cac:TenderingTerms_" element, along with a short description,
indicative cardinalitiesfootnote:[For readability and quick access, the number of columns has been reduced and cardinalities synthetized. While further details may be provided in the explanations after the table, the Annexes of the Regulation will remain the reference.]
and the relative XPATH to the node(s) used to mark it.

Cardinalities are expressed using the following notation:

[cols="^.^10%,<.^40%,^.^10%,<.^40%",]
[%noheader]
|===
s|? |_Optional (0 or 1)_ s|* |_Optional repeatable (0 or more)_

s|1 |_Mandatory & unique (only one)_ s|+ |_Mandatory repeatable (1 or
more)_

s|-- |_Not allowed (0)_ a|(+++*+++) +
(+++**+++) |_Table notes_

|===

[[tenderingTermsRelatedInformationTable]]
.Tendering terms related information
[cols="<.^,^.^,^.^,^.^,^.^,^.^,^.^,^.^,^.^,^.^,<.^",]
[%noheader]
|===
.2+^|*eForms BT* .2+|*Details* .2+|*Procedure* 3+|*PIN* 2+|*CN* 2+|*CAN* .2+|*XSD element*
|G.Lot |Lot |Part |G.Lot |Lot |G.Lot |Lot

11+^|*Selection Criteria (++*++)* 

|*Selection Criteria Type (BT-747)* |xref:selectionCriteriaSection[xrefstyle=short] |-- |-- |*?* |-- |-- |*?* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/cbc:CriterionTypeCode
----

|*Selection Criteria Name (BT-749)* |xref:selectionCriteriaSection[xrefstyle=short] |-- |-- |*?* |-- |-- |*?* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/cbc:Name
----

|*Selection Criteria Description (BT-750)* |xref:selectionCriteriaSection[xrefstyle=short] |-- |-- |*?* |-- |-- |*?* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/cbc:Description
----

|*Selection Criteria Used (BT-748)* | xref:selectionCriteriaSection[xrefstyle=short] |-- |-- |*?* |-- |-- |*?* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/cbc:CalculationExpressionCode
----


11+^|*Second Stage Invite* 

|*Selection Criteria Second Stage Invite (BT-40)* | xref:selectionCriteriaSection[xrefstyle=short] |-- |-- |*?* |-- |-- |*?* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/efbc:SecondStageIndicator
----

|*Selection Criteria Second Stage Invite Number Weight (BT-7531)* | xref:selectionCriteriaSection[xrefstyle=short] |-- |-- h|* |-- |-- h|* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria[*]{zwsp}/efac:CriterionParameter{zwsp}/efbc:ParameterCode{zwsp}[@listName="number-weight"]
----


|*Selection Criteria Second Stage Invite Number Threshold (BT-7532)* | xref:selectionCriteriaSection[xrefstyle=short] |-- |-- h|* |-- |-- h|* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria[*]{zwsp}/efac:CriterionParameter{zwsp}/efbc:ParameterCode{zwsp}[@listName="number-threshold"]
----


|*Selection Criteria Second Stage Invite Number (BT-752)* | xref:selectionCriteriaSection[xrefstyle=short] 
|-- |-- h|* |-- |-- h|* |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:SelectionCriteria{zwsp}/efac:CriterionParameter{zwsp}/efbc:ParameterNumeric
----


11+^|*Misc. terms (++*++)*

|*Variants (BT-63)* | xref:variantsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cbc:VariantConstraintCode
----

|*EU Funds (BT-60)* | xref:EUFundsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|?
a|
[source,xpath,subs=attributes]
----
cbc:FundingProgramCode{zwsp}[@listName='eu-funded']
----


|*Performing Staff Qualification (BT-79)* | xref:staffQualificationSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:RequiredCurriculaCode
----

|*Recurrence (BT-94)* | xref:recurrenceSection[xrefstyle=short] |-- |-- |-- |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cbc:RecurringProcurementIndicator
----

|*Recurrence Description (BT-95)* | xref:recurrenceSection[xrefstyle=short] |-- |-- |-- |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:RecurringProcurementDescription
----

|*Security Clearance Deadline (BT-78)* | xref:clearanceDeadlineSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:LatestSecurityClearanceDate
----

|*Multiple Tenders (BT-769)* | xref:multipleTendersSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:MultipleTendersCode
----


11+^|*Financial guarantee (+++**+++)* 

|*Guarantee Required (BT-751)* | xref:financialGuaranteeSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:RequiredFinancialGuarantee{zwsp}/cbc:GuaranteeTypeCode
----

|*Guarantee Required Description (BT-75)* | xref:financialGuaranteeSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:RequiredFinancialGuarantee{zwsp}/cbc:Description
----


11+^|*Procurement documents (+++**+++)*

|*Documents Restricted Justification (BT-707)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}[cbc:DocumentType/text()='restricted-document']{zwsp}/cbc:DocumentTypeCode{zwsp}[@listName='communication-justification']
----


|*Documents Official Language (BT-708)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}/cbc:LanguageID
----

|*Documents Unofficial Language (BT-737)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}/cbc:LanguageID
----
AND
[source,xpath,subs=attributes]
----
cbc:DocumentStatusCode with value "non-official"
----

|*Documents Restricted (BT-14)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}/cbc:DocumentType{zwsp}[./text()='restricted-document']
----


|*Documents URL (BT-15)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}/cac:Attachment{zwsp}/cac:ExternalReference{zwsp}/cbc:URI
----

|*Documents Restricted URL (BT-615)* | xref:procurementDocsSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:CallForTendersDocumentReference{zwsp}[cbc:DocumentType/text()='restricted-document']{zwsp}/cac:Attachment{zwsp}/cac:ExternalReference{zwsp}/cbc:URI
----


11+^|*Financial terms (+++**+++)*

|*Terms Financial (BT-77)* | xref:termsFinancialSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:PaymentTerms{zwsp}/cbc:Note
----


11+^|*Participation, exclusion & legal (+++**+++)*

|*Cross Border Law (BT-09)* | xref:crossBorderLawSection[xrefstyle=short] h|* |-- |-- |-- |-- |-- |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ProcurementLegislationDocumentReference{zwsp}/cbc:DocumentDescription
----

|*Legal Basis (BT-01) -- Local - Code* | xref:otherLegalBasisSection[xrefstyle=short] h|* |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ProcurementLegislationDocumentReference{zwsp}/cbc:ID
----

|*Legal Basis (BT-01) -- Local - Text* | xref:otherLegalBasisSection[xrefstyle=short] h|* |-- |-- |-- |-- |-- |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ProcurementLegislationDocumentReference{zwsp}/cbc:DocumentDescription
----

|*Exclusion Grounds (BT-67)* | xref:reservedParticipationSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cac:SpecificTendererRequirement{zwsp}/cbc:TendererRequirementTypeCode{zwsp}[@listName='exclusion-ground']
----
AND
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cac:SpecificTendererRequirement{zwsp}/cbc:Description
----

|*Reserved Participation (BT-71)* | xref:reservedParticipationSection[xrefstyle=short] |-- |-- h|+ |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cac:SpecificTendererRequirement{zwsp}/cbc:TendererRequirementTypeCode{zwsp}[@listName="reserved-procurement"]
----


11+^|*Tenderer requirement (+++**+++)*

|*Tenderer Legal Form (BT-761)* | xref:tendererReqsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cbc:CompanyLegalFormCode
----

|*Tenderer Legal Form Description (BT-76)* | xref:tendererReqsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cbc:CompanyLegalForm
----

|*Late Tenderer Information (BT-771)* | xref:tendererReqsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cac:SpecificTendererRequirement{zwsp}/cbc:TendererRequirementTypeCode
----

|*Late Tenderer Information Description (BT-772)* | xref:tendererReqsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:TendererQualificationRequest{zwsp}/cac:SpecificTendererRequirement{zwsp}/cbc:Description
----


11+^|*Subcontracting obligations (Dir. 81 only) (+++**+++)*

|*Subcontracting Tender Indication (BT-651)* | xref:subcontractingObligationSection[xrefstyle=short] |-- |-- h|* |-- |-- h|+ |-- |--
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:TenderSubcontractingRequirements{zwsp}/efbc:TenderSubcontractingRequirementsCode{zwsp}[@listName="subcontracting-indication"]
----


|*Subcontracting Obligation (BT-65)* | xref:subcontractingObligationSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:AllowedSubcontractTerms{zwsp}/cbc:SubcontractingConditionsCode
----

|*Subcontracting Obligation Maximum (BT-729)* | xref:subcontractingObligationSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AllowedSubcontractTerms{zwsp}/cbc:MaximumPercent
----

|*Subcontracting Obligation Minimum (BT-64)* | xref:subcontractingObligationSection[xrefstyle=short] |-- |-- h|? |-- |-- h|1 |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AllowedSubcontractTerms{zwsp}/cbc:MinimumPercent
----


11+^|*Execution requirements (+++**+++)*

|*Reserved Execution (BT-736)* | xref:reservedExecutionSection[xrefstyle=short] |-- |-- h|1 |-- |-- h|1 |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ContractExecutionRequirement{zwsp}/cbc:ExecutionRequirementCode{zwsp}[@listName='reserved-execution']
----


|*Electronic Invoicing (BT-743)* | xref:eInvoicingSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ContractExecutionRequirement{zwsp}/cbc:ExecutionRequirementCode{zwsp}[@listName='einvoicing']
----


|*Terms Performance (BT-70)* | xref:termsPerformanceSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ContractExecutionRequirement{zwsp}/cbc:Description
----

|*Submission Electronic Catalog (BT-764)* | xref:eCatalogueSubmissionSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ContractExecutionRequirement{zwsp}/cbc:ExecutionRequirementCode{zwsp}[@listName='ecatalog-submission']
----


|*Submission Electronic Signature (BT-744)* | xref:eSignatureSubmissionSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:ContractExecutionRequirement{zwsp}/cbc:ExecutionRequirementCode{zwsp}[@listName='esignature-submission']
----


11+^|*Awarding consequences (+++**+++)*

|*Following Contract (BT-41)* | xref:awardConsequencesSection[xrefstyle=short] |-- |-- |-- |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cbc:FollowupContractIndicator
----

|*Jury Decision Binding (BT-42)* | xref:awardConsequencesSection[xrefstyle=short] |-- |-- |-- |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cbc:BindingOnBuyerIndicator
----

|*No Negotiation Necessary (BT-120)* | xref:awardConsequencesSection[xrefstyle=short] |-- |-- |-- |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cbc:NoFurtherNegotiationIndicator
----


11+^|*Award Criteria (+++**+++)*

|*Award Criteria Order Justification (BT-733)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:AwardingCriterion{zwsp}/cbc:Description
----

|*Award Criteria Complicated (BT-543)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cbc:CalculationExpression
----

|*Award Criterion Number Weight (BT-5421)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:AwardCriterionParameter{zwsp}/efbc:ParameterCode
----

|*Award Criterion Number Fixed (BT-5422)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:AwardCriterionParameter{zwsp}/efbc:ParameterCode
----

|*Award Criterion Number Threshold (BT-5423)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:AwardCriterionParameter{zwsp}/efbc:ParameterCode
----

|*Award Criterion Number (BT-541)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:AwardCriterionParameter{zwsp}/efbc:ParameterNumeric
----

|*Award Criterion Type (BT-539)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/cbc:AwardingCriterionTypeCode
----

|*Award Criterion Name (BT-734)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/cbc:Name
----

|*Award Criterion Description (BT-540)* | xref:awardCriteriaSection[xrefstyle=short] |-- h|? h|? |-- h|? h|? h|? h|? 
a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:AwardingCriterion{zwsp}/cac:SubordinateAwardingCriterion{zwsp}/cbc:Description
----


11+^|*Jury (+++**+++)*

|*Jury Member Name (BT-46)* | xref:jurySection[xrefstyle=short] |-- |-- |-- |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:TechnicalCommitteePerson{zwsp}/cbc:FamilyName
----


11+^|*Prize information (CN Design per prize) (+++**+++)*

|*Prize Rank (BT-44)* | xref:prizeSection[xrefstyle=short] |-- |-- |-- |-- |-- h|1 |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:Prize{zwsp}/cbc:RankCode
----

|*Value Prize (BT-644)* | xref:prizeSection[xrefstyle=short] |-- |-- |-- |-- |-- h|1 |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:Prize{zwsp}/cbc:ValueAmount
----

|*Rewards Other (BT-45)* | xref:prizeSection[xrefstyle=short] |-- |-- |-- |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AwardingTerms{zwsp}/cac:Prize{zwsp}/cbc:Description
----


11+^|*Tenders processing parties (+++**+++)*

a|
*_Organization providing additional information _*

_(Organization subrole)_

|_xref:processingPartiesSection[xrefstyle=short]_ |-- |-- h|? h|? |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:AdditionalInformationParty
----

|*_Organization providing offline access to the procurement documents_*
|_xref:processingPartiesSection[xrefstyle=short]_ |-- |-- h|? h|? |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:DocumentProviderParty
----


a|
*_Organization receiving tenders {zwsp}/ Requests to participate_*

_(Organization subrole)_

|_xref:processingPartiesSection[xrefstyle=short]_ |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:TenderRecipientParty
----

|*Submission URL (BT-18)* | xref:processingPartiesSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:TenderRecipientParty{zwsp}/cbc:EndpointID
----


a|
*_Organization processing tenders {zwsp}/ Requests to participate_*

_(Organization subrole)_

|_xref:processingPartiesSection[xrefstyle=short]_ |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:TenderEvaluationParty
----


11+^|*Tender validity (+++**+++)*

|*Tender Validity Deadline (BT-98)* | xref:tenderValiditySection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:TenderValidityPeriod{zwsp}/cbc:DurationMeasure
----


11+^|*Appeal terms (+++**+++)*

|*Review Deadline Description (BT-99)* | xref:appealTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|?
a|
[source,xpath,subs=attributes]
----
cac:AppealTerms{zwsp}/cac:PresentationPeriod{zwsp}/cbc:Description
----


a|
*Review organization *

_(Organization role)_

| xref:appealTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|?
a|
[source,xpath,subs=attributes]
----
cac:AppealTerms{zwsp}/cac:AppealReceiverParty
----


a|
*Organization providing more information on the time limits for review*

_(Organization subrole)_

| xref:appealTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|?
a|
[source,xpath,subs=attributes]
----
cac:AppealTerms{zwsp}/cac:AppealInformationParty
----


a|
*Mediation Organization*

_(Organization role)_

| xref:appealTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|?
a|
[source,xpath,subs=attributes]
----
cac:AppealTerms{zwsp}/cac:MediationParty
----


11+^|*Tendering language (+++**+++)*

|*Submission Language (BT-97)* | xref:postAwardSection[xrefstyle=short] |-- |-- h|+ |-- |-- h|+ |-- |-- a|
[source,xpath,subs=attributes]
----
cac:Language{zwsp}/cbc:ID
----


11+^|*Lots distribution (+++**+++)*

|*Lots Max Awarded (BT-33)* | xref:maxLotsSection[xrefstyle=short] h|1 |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:LotDistribution{zwsp}/cbc:MaximumLotsAwardedNumeric
----

|*Lots Max Allowed (BT-31)* | xref:maxLotsSection[xrefstyle=short] h|1 |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:LotDistribution{zwsp}/cbc:MaximumLotsSubmittedNumeric
----

11+^|*Group definition* 

|*Group Identifier (BT-330)* | xref:maxLotsSection[xrefstyle=short] h|1 |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:LotDistribution{zwsp}/cac:LotsGroup{zwsp}/cbc:ID
----

|*Group Lot Identifier (BT-1375)* | xref:maxLotsSection[xrefstyle=short] h|1 |-- |-- |-- |-- |-- |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:LotDistribution{zwsp}/cac:LotsGroup{zwsp}/cac:ProcurementProjectLotReference{zwsp}/cbc:ID
----


11+^|*Post award process (+++**+++)*

|*Electronic Ordering (BT-92)* | xref:postAwardSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:PostAwardProcess{zwsp}/cbc:ElectronicOrderUsageIndicator
----

|*Electronic Payment (BT-93)* | xref:postAwardSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:PostAwardProcess{zwsp}/cbc:ElectronicPaymentUsageIndicator
----


11+^|*Participants (+++**+++)* 

|*Participant Name (BT-47)* | xref:shortlistSection[xrefstyle=short] |-- |-- |-- |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cac:EconomicOperatorShortList{zwsp}/cac:PreSelectedParty{zwsp}/cac:PartyName{zwsp}/cbc:Name
----


11+^|*Security Clearance (+++**+++)*

|*Security Clearance Code (BT-578)* | xref:securityClearanceSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:SecurityClearanceTerm{zwsp}/cbc:Code
----

|*Security Clearance Description (BT-732)* | xref:securityClearanceSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xapth,subs=attributes]
----
cac:SecurityClearanceTerm{zwsp}/cbc:Description
----

11+a|

*Contexts:*

(+++*+++)

[source,xpath,subs=attributes]
----
/PriorInformationNotice{zwsp}/cac:ProcurementProjectLot{zwsp}/cac:TenderingTerms{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension/

/ContractNotice{zwsp}/cac:ProcurementProjectLot{zwsp}/cac:TenderingTerms{zwsp}/ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension/
----

(+++**+++)

[source,xpath,subs=attributes]
----
/*{zwsp}/cac:TenderingTerms/

/*{zwsp}/cac:ProcurementProjectLot{zwsp}/cac:TenderingTerms/
----

|===



[[selectionCriteriaSection]]
=== Selection criteria

Selection criteria may apply at "_Group of Lots_" and/or "_Lot_" level.
When the Group may not be sub-divided, it is enough to have the criteria
expressed at Group level only. When Lots of a Group may be awarded
individually, it may be necessary to distinguish Group and Lots, and
have criteria expressed for bothfootnote:[The same logic applies to awarding criteria, and the way tenders for the group will be compared to tenders for lots shall be explicitly stated.].

There are different types of selection criteria (BT-747), and the main
ones are "Technical", "Financial" and "Professional". Each of these
categories is respectively encoded with the "tp-abil", "ef-stand" and
"sui-act" value of the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/selection-criterion[selection-criterion] codelistfootnote:[For criteria that would not fit into any of the three previous categories, the value "other" is also available.].
This information is marked using the "_cbc:CriterionTypeCode_" element.

A name (BT-749) may be given to a single selection criterion (or to a
group of them). When specified, the name, of type text, must be provided
in all linguistic versions identified as official languages for the
notice. Information is marked with the "_cbc:Name_" element.

The criteria brief description (BT-750) includes:

* minimum requirements,

* required information (e.g. self-declaration, documentation)
and

* criteria usage for selection of candidates to be invited for
the second stage of the procedure (if a maximum number of candidates was
set).

It shall be provided when the criteria is used (i.e. code "used" from
the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/usage[usage]
codelist; BT-748). The "nyk" value to express that the use of the
criteria/criterion is "not yet known", is only allowed for "PIN time
limit" and "PIN CFC" notices. Further information is marked with the
"_cbc:Description_" element.

When the criteria/criterion is used for selection of candidates for a
second stage ("_efbc:SecondStageIndicator_" set to "_true_", BT-40),
then details about the criteria/criterion associated numbers must be
provided (BT-7531, BT-7532, BT-752).

These details are reported in the efac:CriterionParameter element. The 
type of criterion is indicated by the efbc:ParameterCode element, with 
BT-7531 Selection Criteria Second Stage Invite Number Weight using one 
of the values from the 
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/number-weight[number-weight]
codelist, and BT-7532 Selection Criteria Second Stage Invite Number 
Threshold using one of the values from the 
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/number-threshold[number-threshold]
codelist. The efbc:ParameterNumeric element shall hold the value 
associated with the criterion. 

When shall second stage information be reported?

1. When this is applicable, also information is mandatory for CN
General under Directive 24

2. If Procedure Type (BT-107) isfootnote:[Possible Procedure codes are from the https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/procurement-procedure-type[Procurement Procedure Type] codelist: "open", "oth-single", "neg-wo-call", "restricted", "neg-w-call", "comp-dial", "innovation", "oth-mult".]:

* _"open"_, _"other single stage procedure"_ or _"negotiated without
prior call for competition"_, then the 2^nd^ stage information is not
allowed,

* different from _"open"_, _"other single stage procedure"_ and
_"negotiated without prior call for competition"_, then the 2nd stage
information may/shall be reported.

[source,xml]
----
<efac:SelectionCriteria>
        <cbc:CriterionTypeCode listName="selection-criterion">ef-stand</cbc:CriterionTypeCode>
        <cbc:Name languageID="ENG">Minimum Turnover</cbc:Name>
        <cbc:Name languageID="FRA">Chiffre d'affaire (HT) minimal</cbc:Name>
        <cbc:Description languageID="ENG">Turnover over contract value rate</cbc:Description>
        <cbc:Description languageID="FRA">Rapport Chiffre d'affaire sur valeur du contrat.</cbc:Description>
        <cbc:CalculationExpressionCode listName="usage">used</cbc:CalculationExpressionCode>
        <efbc:SecondStageIndicator>true</efbc:SecondStageIndicator>
        <efac:CriterionParameter>
            <efbc:ParameterCode listName="number-threshold">min-score</efbc:ParameterCode>
            <efbc:ParameterNumeric>2</efbc:ParameterNumeric>
        </efac:CriterionParameter>
    </efac:SelectionCriteria>
    <efac:SelectionCriteria>
        <cbc:CriterionTypeCode listName="selection-criterion">tp-abil</cbc:CriterionTypeCode>
        <cbc:Name languageID="ENG">Experience with similar projects</cbc:Name>
        <cbc:Name languageID="FRA">Expérience avec des projets similaires</cbc:Name>
        <cbc:Description languageID="ENG">Minimum number of years of experience on similar projects</cbc:Description>
        <cbc:Description languageID="FRA">Nombre minimal d'années d'expérience avec des projets similaires</cbc:Description>
        <cbc:CalculationExpressionCode listName="usage">used</cbc:CalculationExpressionCode>
        <efbc:SecondStageIndicator>true</efbc:SecondStageIndicator>
        <efac:CriterionParameter>
            <efbc:ParameterCode listName="number-threshold">min-score</efbc:ParameterCode>
            <efbc:ParameterNumeric>5</efbc:ParameterNumeric>
        </efac:CriterionParameter>
    </efac:SelectionCriteria>
----

[[variantsSection]]
=== Variants (BT-63)

The Variants business term is used to specify whether tenderers are
"allowed", "not allowed" or "required" to provide tenders fulfilling the
needs a different way than the one exposed in the procurement documents.
Code values are listed in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission[permission]
codelist and the BT is expressed as follows:

[source,xml]
----
<cbc:VariantConstraintCode listName="permission">allowed</cbc:VariantConstraintCode>
----

[[EUFundsSection]]
=== EU Funds (BG-61)

In all notices, the element "_cbc:FundingProgramCode_" is used at Lot
(outside the Awarded tender context) to specify whether it is foreseen
or not to have the procurement project partly financed with EU Funds
(BT-60). The value "eu-funds" is used to specify the intention to get
the project partly funded with EU funds (i.e. "true" value for the
indicator), and "no-eu-funds" to indicate that no EU funds is foreseen
for financing the procurement project (i.e. "false" value for the
indicator).

[source,xml]
----
<cbc:FundingProgramCode listName="eu-funded">eu-funds</cbc:FundingProgramCode>
----

[[staffQualificationSection]]
=== Performing Staff Qualification (BT-79)

To indicate whether supporting information for staff qualification shall
be provided, or not, and when (e.g. with the _tender_, with the
_Request To Participate,_ ...); the requirement shall be marked as
follows:

[source,xml]
----
<cbc:RequiredCurriculaCode listName="requirement-stage">t-requ</cbc:RequiredCurriculaCode>
----

Allowed values are those listed in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/requirement-stage[requirement-stage]
codelist.

[[recurrenceSection]]
=== Recurrence (BT-94) and Recurrence Description (BT-95)

For QS and CN Notices (design excluded), the Recurrence (BT-94) may be
used to identify a Procurement whose purpose is likely to also be
included in another procedure in the foreseeable future. Any additional
information about recurrence (e.g. estimated timing) may be reported
using the Recurrence Description (BT-95).

[source,xml]
----
<cbc:RecurringProcurementIndicator>true</cbc:RecurringProcurementIndicator>
<cbc:RecurringProcurementDescription languageID="ENG">The current procurement ...</cbc:RecurringProcurementDescription>
<cbc:RecurringProcurementDescription languageID="FRA">Le marché courant ...</cbc:RecurringProcurementDescription>
----

[[clearanceDeadlineSection]]
=== Clearance Deadline (BT-78)

The time limit by which tenderers not holding the required security
clearances may obtain them is identified with the Business Term Security
Clearance Deadline (BT-78) and marked with the element
"_cbc:LatestSecurityClearanceDate_":

[source,xml]
----
<cbc:LatestSecurityClearanceDate>2019-11-15+01:00</cbc:LatestSecurityClearanceDate>
----

[[multipleTendersSection]]
=== Multiple Tenders (BT-769)

The Multiple Tenders business term allows to specify for a given Lot
whether a tenderer may submit more than one tender ("allowed") or not
("not-allowed"). This information is marked using the
"_cbc:MultipleTendersCode_" for which only the two previous values of
the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission[permission]
codelist are accepted.

[source,xml]
----
<cbc:MultipleTendersCode listName="permission">allowed</cbc:MultipleTendersCode>
----

[[financialGuaranteeSection]]
=== Financial guarantee (BT-751, BT-75)

Whether a provisional guarantee (BT-751) is required, or not, shall be
specified using the element "_cbc:GuaranteeTypeCode_" with
"tender-guarantee-required" as listName attribute and the appropriate
indicator (i.e. true/false); when "true", its description (BT-75) shall
also be provided:

[source,xml]
----
<cac:RequiredFinancialGuarantee>
    <cbc:GuaranteeTypeCode listName="tender-guarantee-required">true</cbc:GuaranteeTypeCode>
    <cbc:Description languageID="ENG">Bids shall include a bid security (Provisional Bank Guarantee or bid bond), ...</cbc:Description>
    <cbc:Description languageID="FRA">Les offres doivent comprendre une garantie de soumission (garantie bancaire provisoire ou caution de soumission), ...</cbc:Description>
</cac:RequiredFinancialGuarantee>
----

[[procurementDocsSection]]
=== Procurement documents (BT-14, BT-15, BT-615, BT-707)

The URL to procurement documents (or to information on documents with
controlled accesses) is marked using the "_cbc:URI_" element.

The identifier "_cbc:ID_" is mandatory and shall not be empty. There is
no predefined structure or list and any relevant value may be used so
long it does not exceed the string length limitation.

The document type code value provides the background reason (BT-707) for
restricted access ("restricted-document" value of the cbc:DocumentType
element, BT-14).

Possible "_cbc:DocumentTypeCode_" values are listed in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/communication-justification[communication-justification]
codelist. When access is not restricted, _cbc:DocumentType_ shall have
the "non-restricted-document" value and the element
_cbc:DocumentTypeCode_ shall not be used.

When there is a need to specify the linguistic version, then the
cbc:LanguageID element has to be used with values from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/language[language]
codelist. This element is not repeatable and when multiple linguistic
versions have to be referenced, the whole block
"_cac:CallForTendersDocumentReference_" has to be repeated.

The status of a given linguistic version may also be specified using the
"_cbc:DocumentStatusCode_" element with either of the two values: "official"
and "non-official".

[source,xml]
----
<cac:CallForTendersDocumentReference>
    <cbc:ID>20210521/CTFD/ENG/7654-02</cbc:ID>
    <cbc:DocumentTypeCode listName="communication-justification">ipr-iss</cbc:DocumentTypeCode>
    <cbc:DocumentType>restricted-document</cbc:DocumentType>
    <cbc:LanguageID>ENG</cbc:LanguageID>
    <cbc:DocumentStatusCode listName="linguistic-status">official</cbc:DocumentStatusCode>
    <cac:Attachment>
        <cac:ExternalReference>
            <cbc:URI>https://mywebsite.com/proc/2019024/accessinfo</cbc:URI>
        </cac:ExternalReference>
    </cac:Attachment>
</cac:CallForTendersDocumentReference>
----

[[termsFinancialSection]]
=== Financial terms (BT-77)

Financing and payment terms, or reference to any provision governing
them, is marked with the "_cbc:Note_" child of the "_cac:PaymentTerms_"
element.

[source,xml]
----
<cac:PaymentTerms>
    <cbc:Note languageID="ENG">Any payment ...</cbc:Note>
    <cbc:Note languageID="FRA">Tout paiement ...</cbc:Note>
</cac:PaymentTerms>
----

[[crossBorderLawSection]]
=== Cross Border Law (Procedure) (BT-09)

To specify applicable cross border law for the procurement involving
buyers from different countries, the information shall be marked
specifying "CrossBorderLaw" in the cbc:ID element with the appropriate
information about the legislation reported in the
"_cbc:DocumentDescription_" text field:

[source,xml]
----
<cac:ProcurementLegislationDocumentReference>
    <cbc:ID>CrossBorderLaw</cbc:ID>
    <cbc:DocumentDescription languageID="ENG">Directive XYZ on Cross Border ...</cbc:DocumentDescription>
    <cbc:DocumentDescription languageID="FRA">La directive XYZ sur les échanges ...</cbc:DocumentDescription>
</cac:ProcurementLegislationDocumentReference>
----

[[otherLegalBasisSection]]
=== Legal Basis (BT-01)

Local legal basis shall be marked the same way as Cross Border Law:

* Specifying the European Legislation Identifier (ELI) in the
cbc:ID element with the appropriate schemeName:

[source,xml]
----
<cac:ProcurementLegislationDocumentReference>
    <cbc:ID schemeName="ELI">http://data.europa.eu/eli/dir/2014/24/oj</cbc:ID>
    <cbc:DocumentDescription languageID="ENG">Directive XYZ applies ...</cbc:DocumentDescription>
    <cbc:DocumentDescription languageID="FRA">La directive XYZ ...</cbc:DocumentDescription>
</cac:ProcurementLegislationDocumentReference>
----

* Or, when ELI is not available, the identifier
"_LocalLegalBasis_" and a short text (description) of applicable law(s):

[source,xml]
----
<cac:ProcurementLegislationDocumentReference>
    <cbc:ID>LocalLegalBasis</cbc:ID>
    <cbc:DocumentDescription languageID="ENG">Directive XYZ applies ...</cbc:DocumentDescription>
    <cbc:DocumentDescription languageID="FRA">La directive XYZ ...</cbc:DocumentDescription>
</cac:ProcurementLegislationDocumentReference>
----

[[reservedParticipationSection]]
=== Exclusion Grounds (BT-67) & Reserved Participation (BT-71)

Both are within the same element and express requirements on the
tenderer itself.

Exclusion Grounds (BT-67) refer to criteria that, not met and justified
(even with self-declaration), lead to the tenderer exclusion. This
information is expected as a code from the technical codelist
"exclusion-ground" built on the ESPD codelist. More than one exclusion
ground may be used, each in a dedicated
"_cac:SpecificTendererRequirement_" element, a given code may however be
used only once. Additionally to the code, a text ("cbc:Description") may
be used.

Reserved Participation (BT-71) expresses a participation restriction;
only tenderers with specific social missions may tender. Information is
encoded with the "_cbc:TendererRequirementTypeCode_" element. Possible
values are from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/reserved-procurement[reserved
procurement] codelist. When multiple restrictions apply, the parent
"_cac:SpecificTendererRequirement_" has to be repeated as many times as
required.

When no Reserved Procurement requirements exist, while the business term
is mandatory, the value "_none_" shall be used and no other "Reserved
Participation" requirement shall be specified.

[source,xml]
----
<cac:TendererQualificationRequest>
    <cac:SpecificTendererRequirement>
        <cbc:TendererRequirementTypeCode listName="exclusion-ground">CRITERION.EXCLUSION.NATIONAL.OTHER</cbc:TendererRequirementTypeCode>
        <cbc:Description languageID="ENG">Applicants not satisfying ...</cbc:Description>
        <cbc:Description languageID="FRA">Les candidats ne satisfaisant pas ...</cbc:Description>
    </cac:SpecificTendererRequirement>
    <cac:SpecificTendererRequirement>
        <cbc:TendererRequirementTypeCode listName="reserved-procurement">none</cbc:TendererRequirementTypeCode>
    </cac:SpecificTendererRequirement>
</cac:TendererQualificationRequest>
----

[[tendererReqsSection]]
=== Tenderer requirements (BT-76, BT-761, BT-771, BT-772)

The existence of a constraint on a legal form that a group of tenderers
awarded a contract has to take (BT-761), is marked with the
"_cbc:CompanyLegalFormCode_" element. It is expressed using either of the
two values "_true_" or "_false_" and specifying "required" as a listName
attribute. When the value is "true", the _Tenderer Legal Form
Description_ (BT-76) is provided and marked using the
"_cbc:CompanyLegalForm_" element.

Information about the tolerance for supporting documents provision after
tender submission (BT-771), is marked with the element
"_cbc:TendererRequirementTypeCode_", a code from the codelist
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/missing-info-submission[missing-info-submission],
and detailed text using "_cbc:Description_" (BT-772).

[source,xml]
----
<cac:TendererQualificationRequest>
    <cbc:CompanyLegalFormCode listName="required">true</cbc:CompanyLegalForm>
    <cbc:CompanyLegalForm languageID="ENG">The tenderer ...</cbc:CompanyLegalForm>
</cac:TendererQualificationRequest>
<cac:TendererQualificationRequest>
    <cbc:CompanyLegalFormCode>true</cbc:CompanyLegalForm>
    <cbc:CompanyLegalForm languageID="FRA">Le soumissionaire ...</cbc:CompanyLegalForm>
</cac:TendererQualificationRequest>
<cac:TendererQualificationRequest>
    <cac:SpecificTendererRequirement>
        <cbc:TendererRequirementTypeCode listName="missing-info-submission">late-all</cbc:TendererRequirementTypeCode>
        <cbc:Description languageID="ENG">Economic operators who ...</cbc:Description>
        <cbc:Description languageID="FRA">Les opérateurs économiques qui ...</cbc:Description>
    </cac:SpecificTendererRequirement>
</cac:TendererQualificationRequest>
----

[[subcontractingObligationSection]]
=== Subcontracting obligations (BT-64, BT-65, BT-651, BT-729)

These elements apply only for Directive 2009/81 notices of notice types
"PIN time limit" and "CN general".

The Subcontracting Obligation (BT-65) expresses, with the
"_cbc:SubcontractingConditionsCode_" element, using a code from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/subcontracting-obligation[subcontracting-obligation]
codelist, the obligations the contractor will have to follow concerning
subcontracting. When the code value is "subc-min"footnote:[meaning that "_The contractor must subcontract a minimum percentage of the contract using the procedure set out in Title III of Directive 2009/81/EC._"],
the Subcontracting Obligation Minimum (BT-64) and Subcontracting
Obligation Maximum (BT-729) shall be specified; when the code value is
"subc-chng"footnote:[meaning that "_The contractor must indicate any change of subcontractors during the execution of the contract._"],
"subc-oblig-2009-81" or "none", no other element shall be associated at
the same level.

Subcontracting Obligation Maximum (BT-729) and Subcontracting Obligation
Minimum (BT-64) are respectively marked using the "_cbc:MaximumPercent_"
and "_cbc:MinimumPercent_" with decimal values.

The expression of multiple complementary obligations is performed with
multiplication of the parent element "_cac:AllowedSubcontractTerms_".

[source,xml]
----
<cac:AllowedSubcontractTerms>
    <cbc:SubcontractingConditionsCode listName="subcontracting-obligation">subc-chng</cbc:SubcontractingConditionsCode>
</cac:AllowedSubcontractTerms>
<cac:AllowedSubcontractTerms>
    <cbc:SubcontractingConditionsCode listName="subcontracting-obligation">subc-min</cbc:SubcontractingConditionsCode>
    <cbc:MaximumPercent>45.5</cbc:MaximumPercent>
    <cbc:MinimumPercent>25.5</cbc:MinimumPercent>
</cac:AllowedSubcontractTerms>
----

Subcontracting Tender Indication (BT-651) provides information about
subcontracting information a tenderer shall specify in its tender; this
is marked with the "_efbc:TenderSubcontractingRequirementsCode_" element;
Allowed code values are listed in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/subcontracting-indication[subcontracting-indication]
codelist.

[source,xml]
----
<ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionContent>
            <efext:EformsExtension>
                <efac:TenderSubcontractingRequirements>
                    <efbc:TenderSubcontractingRequirementsCode listName="subcontracting-indication">subc-oblig</efbc:TenderSubcontractingRequirementsCode>
                </efac:TenderSubcontractingRequirements>
                <efac:TenderSubcontractingRequirements>
                    <efbc:TenderSubcontractingRequirementsCode listName="subcontracting-indication">subj-noblig</efbc:TenderSubcontractingRequirementsCode>
                </efac:TenderSubcontractingRequirements>
            </efext:EformsExtension>
        </ext:ExtensionContent>
    </ext:UBLExtension>
</ext:UBLExtensions>
----

[[reservedExecutionSection]]
=== Reserved Execution (BT-736)

This element is used to specify whether the procurement execution is
reserved or not, or whether this is not yet known. The element must be
specified everywhere mandated by the Regulation. The values should be
"yes", "no" or "not-known". Values come from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/applicability[applicability]
codelist:

[source,xml]
----
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="reserved-execution">not-known</cbc:ExecutionRequirementCode>
</cac:ContractExecutionRequirement>
----

[[eInvoicingSection]]
=== Electronic Invoicing (BT-743)

Use of e-invoicing for the contract execution is encoded with the
"_cbc:ExecutionRequirementCode_" element, the code value selected from
the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission[permission]
codelist:

[source,xml]
----
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="einvoicing">required</cbc:ExecutionRequirementCode>
</cac:ContractExecutionRequirement>
----

[[termsPerformanceSection]]
=== Terms Performance (BT-70)

The main information about the performance of the contract (e.g.
intermediary deliverables, compensation for damages, intellectual
property rights) shall be marked:

[source,xml]
----
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="conditions">performance</cbc:ExecutionRequirementCode>
    <cbc:Description languageID="ENG">During execution of the contract, ...</cbc:Description>
    <cbc:Description languageID="FRA">Pendant l'exécution du contrat, ...</cbc:Description>
</cac:ContractExecutionRequirement>
----

[[eCatalogueSubmissionSection]]
=== Submission Electronic Catalogue (BT-764)

The possibility to submit (parts of) tenders as electronic catalogues is
specified with the "_cbc:ExecutionRequirementCode_" element, having its
"listName" attribute set to "ecatalog-submission", with the value
selected from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission[permission]
codelist:

[source,xml]
----
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="ecatalog-submission">allowed</cbc:ExecutionRequirementCode>
</cac:ContractExecutionRequirement>
----

[[eSignatureSubmissionSection]]
=== Submission Electronic Signature (BT-744)

Whether or not the use of electronic signaturefootnote:[as defined in Regulation (EU) No 910/2014] is required, is indicated by a "true"/"false" value in the "_cbc:ExecutionRequirementCode_" element, having its "listName" attribute set to "_esignature-submission_":

[source,xml]
----
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="esignature-submission">false</cbc:ExecutionRequirementCode>
</cac:ContractExecutionRequirement>
----

[[maxLotsSection]]
=== Lots Max Awarded (BT-33), Lots Max Allowed (BT-31) & Group of ##Lots definition

Regarding Lots distribution, relevant information is:

* The maximum number of Lots that can be awarded to one economic
operator,

* The maximum number of Lots that one economic operator can
submit a tender for,

* The grouping of Lots.

Restrictions and Group of Lots should only be specified when applicable.

[source,xml]
----
<cac:LotDistribution>
    <cbc:MaximumLotsAwardedNumeric>4</cbc:MaximumLotsAwardedNumeric>
    <cbc:MaximumLotsSubmittedNumeric>6</cbc:MaximumLotsSubmittedNumeric>
    <cac:LotsGroup>
        <!-- Definition of Group of Lots 1 -->
        <cbc:LotsGroupID schemeName="LotsGroup">GLO-0001</cbc:LotsGroupID>
        <cac:ProcurementProjectLotReference>
            <cbc:ID schemeName="Lot">LOT-0002</cbc:ID>
        </cac:ProcurementProjectLotReference>
        <cac:ProcurementProjectLotReference>
            <cbc:ID schemeName="Lot">LOT-0005</cbc:ID>
        </cac:ProcurementProjectLotReference>
        <cac:ProcurementProjectLotReference>
            <cbc:ID schemeName="Lot">LOT-0006</cbc:ID>
        </cac:ProcurementProjectLotReference>
    </cac:LotsGroup>
    <cac:LotsGroup>
        <!-- Definition of Group of Lots 2 -->
        <cbc:LotsGroupID schemeName="LotsGroup">GLO-0002</cbc:LotsGroupID>
        <cac:ProcurementProjectLotReference>
            <cbc:ID schemeName="Lot">LOT-0002</cbc:ID>
        </cac:ProcurementProjectLotReference>
        <cac:ProcurementProjectLotReference>
            <cbc:ID schemeName="Lot">LOT-0005</cbc:ID>
        </cac:ProcurementProjectLotReference>
    </cac:LotsGroup>
</cac:LotDistribution>
----

Considerations:

* The "maximum number of tenderable Lots per economic operator"
shall be equal or greater than the "maximum number of awardable Lots per
economic operator";

* No Group of Lots may contain more Lots than the maximum number
of awardable Lots per economic operator; otherwise the Group of Lots
would not be awardable;

* A Group of Lots shall only contain Lots (i.e. no Group of
Lots);

* A "PIN only" notice shall not have any Group of Lots;

* Any Group of Lots shall have at least 2 Lots;

* Two different Groups of Lots may contain the same Lot; in such
a situation, these will compete at the time of tenders evaluation;

[[awardConsequencesSection]]
=== Awarding consequences (BT-41, BT-42, BT-120)

Awarding consequences like:

* Following Contract (BT-41)

* Jury Decision Binding (BT-42)

* No Negotiation Necessary (BT-120)

Shall be respectively marked using the indicators:

* __cbc:FollowupContractIndicator__,

* __cbc:BindingOnBuyerIndicator__, and

* __cbc:NoFurtherNegotiationIndicator__.

[source,xml]
----
<cbc:FollowupContractIndicator>true</cbc:FollowupContractIndicator>
<cbc:BindingOnBuyerIndicator>true</cbc:BindingOnBuyerIndicator>
<cbc:NoFurtherNegotiationIndicator>true</cbc:NoFurtherNegotiationIndicator>
----

[[awardCriteriaSection]]
=== Award Criteria (BT-539, BT-540, BT-541, BT-543, BT-733, BT-734, BT-5421, BT-5422, BT-5423)

The way Award criteria is marked has some similarities with Selection
criteria (cf. <<selectionCriteriaSection>>), they however have some additional dedicated
elements.

When the use of Award Criteria is performed sequentially based on order
of importance instead of involving weighted scores, the buyer shall
justify this decision (BT-733) using the "_cbc:Description_" element of
"_cac:AwardingCriterion_".

[source,xml]
----
<cac:AwardingCriterion>
    <cbc:Description languageID="ENG">Each criterion is evaluated separately ...</cbc:Description>
    <cbc:Description languageID="FRA">Chaque critère est évalué individuellement ...</cbc:Description>
    <cac:SubordinateAwardingCriterion>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionContent>
                    <efext:EformsExtension>
                        <efac:AwardCriterionParameter>
                            <efbc:ParameterCode listName="number-threshold">min-pass</efbc:ParameterCode>
                            <efbc:ParameterNumeric>50</efbc:ParameterNumeric>
                        </efac:AwardCriterionParameter>
                    </efext:EformsExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:AwardingCriterionTypeCode listName="award-criterion-type">price</cbc:AwardingCriterionTypeCode>
        <cbc:Name languageID="ENG">Fair & realistic price</cbc:Name>
        <cbc:Name languageID="FRA">Prix équitable et réaliste</cbc:Name>
        <cbc:Description languageID="ENG">Tenders with a price score lower than 50 ...</cbc:Description>
        <cbc:Description languageID="FRA">Les offres avec un score sur les prix infèrieur ...</cbc:Description>
    </cac:SubordinateAwardingCriterion>
    <cac:SubordinateAwardingCriterion>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionContent>
                    <efext:EformsExtension>
                        <efac:AwardCriterionParameter>
                            <efbc:ParameterCode listName="number-threshold">min-pass</efbc:ParameterCode>
                            <efbc:ParameterNumeric>65</efbc:ParameterNumeric>
                        </efac:AwardCriterionParameter>
                    </efext:EformsExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:AwardingCriterionTypeCode listName="award-criterion-type">quality</cbc:AwardingCriterionTypeCode>
        <cbc:Name languageID="ENG">Technical merit</cbc:Name>
        <cbc:Name languageID="FRA">Mérite technique</cbc:Name>
        <cbc:Description languageID="ENG">Tenders with a quality score lower than 65 ...</cbc:Description>
        <cbc:Description languageID="FRA">Les offres avec un score qualité infèrieur ...</cbc:Description>
    </cac:SubordinateAwardingCriterion>
</cac:AwardingCriterion>
----

When Award Criteria calculation is more complex (BT-543), then the
complicated expression should either be provided here or there should at
least be a reference to the procurement document section where this
information may be found. Information is encoded as text with the
element "_cbc:CalculationExpression_"; for a given
"_cac:AwardingCriterion_" element, the children "_cbc:Description_" (BT-733)
and "_cbc:CalculationExpression_" (BT-543) shall not coexist.

For any criterion of the award criteria, the type (BT-539) and
description (BT-540) shall be provided; the name (BT-734) is however
optional. The type of award criterion shall be one of the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/award-criterion-type[award-criterion-type]
codelist.

This criterion may be quantified in one or more dimensions, each within 
an efac:AwardCriterionParameter element. The dimension is specified with 
the efbc:ParameterCode element, and the efbc:ParameterNumeric element 
shall hold the value associated with that dimension.


The number dimension shall be:

* for weights (BT-5421), elements from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/number-weight[number-weight]
codelist;

* for fixed values (BT-5422), elements from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/number-fixed[number-fixed]
codelist; and

* for threshold values (BT-5423), elements from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/number-threshold[number-threshold]
codelist.

[source,xml]
----
<cac:AwardingCriterion>
    <cbc:CalculationExpression languageID="ENG">Price-quality score calculation is based on ...</cbc:CalculationExpression>
    <cbc:CalculationExpression languageID="FRA">Le calcul du score prix-qualité est basée sur ...</cbc:CalculationExpression>
    <cac:SubordinateAwardingCriterion>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionContent>
                    <efext:EformsExtension>
                        <efac:AwardCriterionParameter>
                            <efbc:ParameterCode listName="number-weight">per-exa</efbc:ParameterCode>
                            <efbc:ParameterNumeric>60</efbc:ParameterNumeric>
                        </efac:AwardCriterionParameter>
                    </efext:EformsExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:AwardingCriterionTypeCode listName="award-criterion-type">price</cbc:AwardingCriterionTypeCode>
        <cbc:Name languageID="ENG">Price</cbc:Name>
        <cbc:Name languageID="FRA">Prix</cbc:Name>
        <cbc:Description languageID="ENG">The price score contributes for 60 % ...</cbc:Description>
        <cbc:Description languageID="FRA">Le score du prix participe pour 60 % ...</cbc:Description>
    </cac:SubordinateAwardingCriterion>
    <cac:SubordinateAwardingCriterion>
        <ext:UBLExtensions>
            <ext:UBLExtension>
                <ext:ExtensionContent>
                    <efext:EformsExtension>
                        <efac:AwardCriterionParameter>
                            <efbc:ParameterCode listName="number-weight">per-exa</efbc:ParameterCode>
                            <efbc:ParameterNumeric>40</efbc:ParameterNumeric>
                        </efac:AwardCriterionParameter>
                    </efext:EformsExtension>
                </ext:ExtensionContent>
            </ext:UBLExtension>
        </ext:UBLExtensions>
        <cbc:AwardingCriterionTypeCode listName="award-criterion-type">quality</cbc:AwardingCriterionTypeCode>
        <cbc:Name languageID="ENG">Quality</cbc:Name>
        <cbc:Name languageID="FRA">Qualité</cbc:Name>
        <cbc:Description languageID="ENG">The quality score contributes for 40 % ...</cbc:Description>
        <cbc:Description languageID="FRA">Le score qualité participe pour 40 % ...</cbc:Description>
    </cac:SubordinateAwardingCriterion>
</cac:AwardingCriterion>
----

[[jurySection]]
=== Jury Member Name (BT-46)

For a contest, Jury composition (BT-46) is described by providing the
name of each member:

[source,xml]
----
<cac:TechnicalCommitteePerson>
    <cbc:FamilyName>Mrs Pamela Smith</cbc:FamilyName>
</cac:TechnicalCommitteePerson>
<cac:TechnicalCommitteePerson>
    <cbc:FamilyName>Mr John Doe</cbc:FamilyName>
</cac:TechnicalCommitteePerson>
----

[[prizeSection]]
=== Prize information (BT-44, BT-45, BT-644)

Prize information is only for notices of type "CN design", and covers
_Prize Rank_ (BT-44), _Value Prize_ (BT-644) and _Rewards Other_
(BT-45); the last one being for prizes not having equivalent monetary
value.

The Prize Rank is marked using "_cbc:RankCode_".

The Value Prize is encoded by specifying currency and amount.

Finally the prize description is provided as text.

[source,xml]
----
<cac:Prize>
    <cbc:RankCode>1</cbc:RankCode>
    <cbc:ValueAmount currencyID="EUR">5000</cbc:ValueAmount>
    <cbc:Description languageID="ENG">The first prize winner will be awarded ...</cbc:Description>
    <cbc:Description languageID="FRA">Le gagnant du 1er prix se verra attribuer ...</cbc:Description>
</cac:Prize>
<cac:Prize>
    <cbc:RankCode>2</cbc:RankCode>
    <cbc:ValueAmount currencyID="EUR">0</cbc:ValueAmount>
    <cbc:Description languageID="ENG">The winners of 2nd rank and below ...</cbc:Description>
    <cbc:Description languageID="FRA">Les gagnants de second rang et au-delà ...</cbc:Description>
</cac:Prize>
----

[[processingPartiesSection]]
=== Tenders processing parties (BT-18)

Other parties that can be involved in processing tenders are:

* the organization that provides additional information
("_cac:AdditionalInformationParty_"),

* the organization receiving tenders
("_cac:TenderRecipientParty_"),

* the organization evaluating tenders
("_cac:TenderEvaluationParty_").

They may then be coded in the instance using elements shown below.

[source,xml]
----
<cac:AdditionalInformationParty>
    <!-- Interrupted Mark-Up -->
</cac:AdditionalInformationParty>
<cac:TenderRecipientParty>
    <!-- Interrupted Mark-Up -->
    <cbc:EndpointID>https://www.acme.com/tender-submission/</cbc:EndpointID>
    <!-- Interrupted Mark-Up -->
</cac:TenderRecipientParty>
<cac:TenderEvaluationParty>
    <!-- Interrupted Mark-Up -->
</cac:TenderEvaluationParty>
----

The mark-up of the information for these organizations is presented in
<<partiesSection>>.

Submission URL (BT-18) is marked using the "_cbc:EndpointID_" child of
the "_cac:TenderRecipientParty_" element.

[[tenderValiditySection]]
=== Tender Validity Deadline (BT-98)

The period, starting from the tender submission deadline, during which
the tender must remain valid is expressed as follows:

[source,xml]
----
<cac:TenderValidityPeriod>
    <cbc:DurationMeasure unitCode="MONTH">4</cbc:DurationMeasure>
</cac:TenderValidityPeriod>
----

The unitCode value is one of the duration measure units existing in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/timeperiod[timeperiod]
codelist. Acceptable codes are: YEAR, MONTH, WEEK, DAY. No combined
value may be used and the chosen unit of measure should allow the
expression of the duration using integers.

[[appealTermsSection]]
=== Appeal terms

Different stakeholders may request a decision review, and such
initiative is subject to a deadline (_Review Deadline Description -- 
BT-99_). The review process involves a Review Organization (collecting
review requests) and a Mediation Organization (dealing with the
expressed concerns). An organization is also available to provide
further information on the Review Request process (identified as the
"_Organization providing more information on the time limits for review
procedures_" in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/organisation-subrole[organization
subrole] codelist).

[source,xml]
----
<cac:AppealTerms>
    <cac:PresentationPeriod>
        <cbc:Description languageID="ENG">Any review request shall be submitted ...</cbc:Description>
        <cbc:Description languageID="FRA">Toute demande de revision doit être ...</cbc:Description>
    </cac:PresentationPeriod>
    <cac:AppealInformationParty>
        <!-- Interrupted Mark-Up -->
    </cac:AppealInformationParty>
    <cac:AppealReceiverParty>
        <!-- Interrupted Mark-Up -->
    </cac:AppealReceiverParty>
    <cac:MediationParty>
        <!-- Interrupted Mark-Up -->
    </cac:MediationParty>
</cac:AppealTerms>
----

[[tenderingLanguageSection]]
=== Tendering language (BT-97)

The languages that may be used to submit tenders (BT-97) shall be marked
using
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/language[language]
codes:

[source,xml]
----
<cac:Language>
    <cbc:ID>ENG</cbc:ID>
</cac:Language>
<cac:Language>
    <cbc:ID>FRA</cbc:ID>
</cac:Language>
----

[[postAwardSection]]
=== Post award process (BT-92, BT-93)

The use of _Electronic Ordering (BT-92)_ and _Payment (BT-93)_ during
execution is specified by two indicators:

[source,xml]
----
<cac:PostAwardProcess>
    <cbc:ElectronicOrderUsageIndicator>true</cbc:ElectronicOrderUsageIndicator>
    <cbc:ElectronicPaymentUsageIndicator>true</cbc:ElectronicPaymentUsageIndicator>
</cac:PostAwardProcess>
----

[[shortlistSection]]
=== Economic Operator Shortlist

The "_cac:EconomicOperatorShortList_" element in the Tendering Terms
block shall not be confused with the one in the Tendering Process one.
Here it is used to specify a list of preselected sellers (Participant
Name BT-47), while in the other context (cf. <<maxCandidatesSection>>), it is used to
specify the limitations that will be applied to establish a short list.

[source,xml]
----
<cac:EconomicOperatorShortList>
    <cac:PreSelectedParty>
        <cac:PartyName>
            <cbc:Name>Mrs L. Hürst</cbc:Name>
        </cac:PartyName>
    </cac:PreSelectedParty>
    <cac:PreSelectedParty>
        <cac:PartyName>
            <cbc:Name>Mr P. Sanchez</cbc:Name>
        </cac:PartyName>
    </cac:PreSelectedParty>
</cac:EconomicOperatorShortList>
----

[[securityClearanceSection]]
=== Security Clearance (BT-578) & Description (BT-732)

The Security Clearance description is marked with the
"_cbc:Description_" element of the "_cac:SecurityClearanceTerm_" for the
associated Lot. It covers information like the required level and
period, and the people concerned. When Security Clearance is required
("true" value for "_cbc:Code_"), then information may be specified using
the "_cbc:Description_" element.

[source,xml]
----
<cac:SecurityClearanceTerm>
    <cbc:Code listName="required">true</cbc:Code>
    <cbc:Description languageID="ENG">"EU Confidential" security clearance of Key Management Personnel must be achieved before access to procurement documents be granted</cbc:Description>
    <cbc:Description languageID="FRA">L'habilitation  sécurité "confidentiel UE" du personnel de direction doit être obtenue avant que l'accès aux documents de passation de marché ne soit accordé.</cbc:Description>
</cac:SecurityClearanceTerm>
----

[[tenderingProcessSection]]
== Tendering Process

For Group of Lots, only two types of information are reported at the
level of the Tendering process:

* Statistics related to the tendering process and referring to
this specific Group of Lots,

* Framework Agreement related information.

[[tenderingProcessRelatedInformationTable]]
.Tendering process related information
[width="100%",cols="<.^10%,^.^9%,^.^9%,^.^9%,^.^9%,^.^9%,^.^9%,^.^9%,^.^9%,^.^9%,<.^9%",]
[%noheader]
|===
.2+^|*eForms BT* .2+|*Details* .2+|*Procedure* 3+|*PIN* 2+|*CN* 2+|*CAN* .2+|*XSD
element*
|G.Lot |Lot |Part |G.Lot |Lot |G.Lot |Lot

11+^|*Miscellaneous (+++*+++)*
|*Procurement Relaunch (BT-634)* |xref:procurementRelaunchSection[xrefstyle=short] h|? |-- |-- |-- |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efbc:ProcedureRelaunchIndicator
----

|*Tool Name (BT-632)* |xref:toolNameSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efbc:AccessToolName
----

|*Deadline Receipt Expressions (BT-630)* |xref:expressionsDeadlineSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|

[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:InterestExpressionReceptionPeriod{zwsp}/cbc:EndDate
----
AND
[source,xpath,subs=attributes]
----
ext:UBLExtensions{zwsp}/ext:UBLExtension{zwsp}/ext:ExtensionContent{zwsp}/efext:EformsExtension{zwsp}/efac:InterestExpressionReceptionPeriod{zwsp}/cbc:EndTime
----

|*Procedure Features (BT-88)* |xref:procedureFeaturesSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:Description
----

|*Procedure Type (BT-105)* |xref:procedureTypeSection[xrefstyle=short] h|1 |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:ProcedureCode
----

|*PIN Competition Termination (BT-756)* |xref:competitionTerminationSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:TerminatedIndicator
----

|*Lots All Required (BT-763)* |xref:allLotsSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:PartPresentationCode
----

|*SubmissionElectronic (BT-17)* |xref:eSubmissionSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:SubmissionMethodCode{zwsp}[@listName='esubmission']
----


|*Successive Reduction Indicator (Procedure) (BT-52)* |xref:successiveReductionSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |--
a|
[source,xpath,subs=attributes]
----
cbc:CandidateReductionConstraintIndicator
----

|*GPA Coverage (BT-115)* |xref:GPASection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cbc:GovernmentAgreementConstraintIndicator
----

|*Tool Atypical URL (BT-124)* |xref:atypicalToolSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:AccessToolsURI
----

|*Deadline Receipt Tenders (BT-131)* |xref:tendersDeadlineSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:TenderSubmissionDeadlinePeriod{zwsp}/cbc:EndDate
----
AND
[source,xpath,subs=attributes]
----
cac:TenderSubmissionDeadlinePeriod{zwsp}/cbc:EndTime
----

|*Dispatch Invitation Tender (BT-130)* |xref:tenderInvitationSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:InvitationSubmissionPeriod{zwsp}/cbc:StartDate
----

|*Dispatch Invitation Interest (BT-631)* |xref:interestInvitationSection[xrefstyle=short] |-- |-- h|? |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ParticipationInvitationPeriod{zwsp}/cbc:StartDate
----

|*Deadline Receipt Requests (BT-1311)* |xref:requestDeadlineSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ParticipationRequestReceptionPeriod{zwsp}/cbc:EndDate
----
AND
[source,xpath,subs=attributes]
----
cac:ParticipationRequestReceptionPeriod{zwsp}/cbc:EndTime
----

|*Additional Information Deadline (BT-13)* |xref:additionalInfoDeadlineSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:AdditionalInformationRequestPeriod{zwsp}/cbc:EndDate
----
AND
[source,xpath,subs=attributes]
----
cac:AdditionalInformationRequestPeriod{zwsp}/cbc:EndTime
----

|*Previous Planning Identifier (BT-125)* |xref:previousPlanningSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:NoticeDocumentReference{zwsp}/cbc:ID
----

|*Previous Planning Part Identifier (BT-1251)* |xref:previousPlanningSection[xrefstyle=short] |-- |-- h|* h|? |-- h|* |-- h|*  
a|
[source,xpath,subs=attributes]
----
cac:NoticeDocumentReference{zwsp}/cbc:ReferencedDocumentInternalAddress
----

|*Submission Nonelectronic Justification (BT-19)* |xref:nonelectronicSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReasonCode{zwsp}[@listName='no-esubmission-justification']
----


|*Submission Nonelectronic Description (BT-745)* |xref:nonelectronicSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}[cbc:ProcessReasonCode{zwsp}/@listName='no-esubmission-justification']{zwsp}/cbc:Description
----


11+^|*Procedure Accelerated Justification (+++*+++) / Direct Award Justification
(also T01 with Direct Award)*

|*Procedure Accelerated (BT-106)* |xref:acceleratedProcedureSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReasonCode{zwsp}[@listName='accelerated-procedure']
----


|*Procedure Accelerated Justification (BT-1351) / Code* |xref:acceleratedProcedureSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReasonCode
----

|*Procedure Accelerated Justification (BT-1351) {zwsp}/ Text* |xref:acceleratedProcedureSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReason
----

|*Direct Award Justification Previous Procedure Identifier (BT-1252)* |xref:directAwardSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:Description
----

|*Direct Award Justification (BT-136) {zwsp}/ Code* |xref:directAwardSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReasonCode
----

|*Direct Award Justification (BT-135) {zwsp}/ Text* |xref:directAwardSection[xrefstyle=short] h|? |-- |-- |-- |-- |-- |-- |-- a|
[source,xpath,subs=attributes]
----
cac:ProcessJustification{zwsp}/cbc:ProcessReason
----


11+^|*Candidates (+++*+++)*

|*Maximum Candidates Indicator (BT-661)* |xref:maxCandidatesSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:EconomicOperatorShortList{zwsp}/cbc:LimitationDescription
----

|*Maximum Candidates (BT-51)* |xref:maxCandidatesSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:EconomicOperatorShortList{zwsp}/cbc:MaximumQuantity
----

|*Minimum Candidates (BT-50)* |xref:maxCandidatesSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:EconomicOperatorShortList{zwsp}/cbc:MinimumQuantity
----


11+^|*Opening event (+++*+++)*

|*Public Opening Date (BT-132)* |xref:openingEventSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:OpenTenderEvent{zwsp}/cbc:OccurrenceDate
----
AND
[source,xpath,subs=attributes]
----
cac:OpenTenderEvent{zwsp}/cbc:OccurrenceTime
----

|*Public Opening Description (BT-134)* |xref:openingEventSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:OpenTenderEvent{zwsp}/cbc:Description
----

|*Public Opening Place (BT-133)* |xref:openingEventSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:OpenTenderEvent{zwsp}/cac:OccurrenceLocation{zwsp}/cbc:Description
----


11+^|*Auction Terms (+++*+++)*

|*Electronic Auction (BT-767)* |xref:auctionTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:AuctionTerms{zwsp}/cbc:AuctionConstraintIndicator
----

|*Electronic Auction Description (BT-122)* |xref:auctionTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AuctionTerms{zwsp}/cbc:Description
----

|*Electronic Auction URL (BT-123)* |xref:auctionTermsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:AuctionTerms{zwsp}/cbc:AuctionURI
----


11+^|*Framework Agreement (+++*+++)*

|*Framework Maximum Participants Number (BT-113)* |xref:frameworkAgreementSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- 
a|
[source,xpath,subs=attributes]
----
cac:FrameworkAgreement{zwsp}/cbc:MaximumOperatorQuantity
----

|*Framework Duration Justification (BT-109)* |xref:frameworkAgreementSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cac:FrameworkAgreement{zwsp}/cbc:Justification
----

|*Group Framework Estimated Maximum Value (BT-157)* |xref:frameworkAgreementSection[xrefstyle=short] |-- h|? |-- |-- h|? |-- h|? |-- 
a|
[source,xpath,subs=attributes]
----
cac:FrameworkAgreement{zwsp}/cbc:EstimatedMaximumValueAmount
----

|*Framework Buyer Categories (BT-111)* |xref:frameworkAgreementSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
cac:FrameworkAgreement{zwsp}/cac:SubsequentProcessTenderRequirement{zwsp}/cbc:Description
----

|*Framework Agreement (BT-765)* |xref:frameworkAgreementSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ContractingSystem{zwsp}/cbc:ContractingSystemTypeCode
----

|*Dynamic Purchasing System (BT-766)* |xref:DPSSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ContractingSystem{zwsp}/cbc:ContractingSystemTypeCode
----

11+a|
*Context:*

(*)
[source,xpath,subs=attributes]
----
/ContractAwardNotice{zwsp}/cac:TenderingProcess{zwsp}/

/ContractAwardNotice{zwsp}/cac:ProcurementProjectLot{zwsp}/cac:TenderingProcess{zwsp}/
----

|===

[[procurementRelaunchSection]]
=== Procurement Relaunch (BT-634)

The Procurement Relaunch indicator (BT-634) may apply at different
levels (Lot & Procedure) to specify that, for the corresponding object,
the process will be restarted.

The "_efbc:ProcedureRelaunchIndicator_" element shall only be used when
"true"; When it applies to the whole procurement, it shall appear in the
"_cac:TenderingProcess_" of the notice (i.e. at notice level) only.
When applied to a Lot, all the individual Lots included in a Group of
Lots with that same lot shall be marked as such, and Group of Lots
containing the Lot, shall not exist anymore.

[source,xml]
----
<cac:TenderingProcess>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <efext:EformsExtension>
                    <efbc:ProcedureRelaunchIndicator>true</efbc:ProcedureRelaunchIndicator>
                    <!--Interrupted Mark-up -->
                </efext:EformsExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!--Interrupted Mark-up -->
</cac:TenderingProcess>
----

[[toolNameSection]]
=== Tool Name (BT-632)

The name of the electronic tool or device used for electronic
communication.

This optional element is to be used, for PIN and CN notices only, in
conjunction with BT-724 & BT-124. It shall be marked using the extension
mechanism at the level of the "_cac:TenderingProcess_" element of the
Lot or Group of Lots it applies to.

[source,xml]
----
<cac:TenderingProcess>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <efext:EformsExtension>
                    <efbc:AccessToolName>AbcKomSoft</efbc:AccessToolName>
                    <!--Interrupted Mark-up -->
                </efext:EformsExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!--Interrupted Mark-up -->
    <cac:TenderingProcess>
----

[[expressionsDeadlineSection]]
=== Deadline Receipt Expressions (BT-630)

The deadline for receipt of expressions of interests is marked using the
extension mechanism at the "_cac:TenderingProcess_" level of the
concerned object:

[source,xml]
----
<cac:TenderingProcess>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <efext:EformsExtension>
                    <!--Interrupted Mark-up -->
                    <efac:InterestExpressionReceptionPeriod>
                        <cbc:EndDate>2019-10-28+01:00</cbc:EndDate>
                        <cbc:EndTime>18:00:00+01:00</cbc:EndTime>
                    </efac:InterestExpressionReceptionPeriod>
                </efext:EformsExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <!--Interrupted Mark-up -->
    <cac:TenderingProcess>
----

[[procedureFeaturesSection]]
=== Procedure Features (BT-88)

This business term describes the main features of the whole Procedure;
it provides information on the individual stage(s) and the availability
of the whole set of applicable rules.

The element applies to the whole Procedure (i.e. does not apply per Lot
or Group of Lots), and is mandatory when the procedure is not one of
those mentioned in the procurement Directives (i.e. for values
"oth-mult" and "oth-single" of the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/procurement-procedure-type[procurement-procedure-type]
codelist).

[source,xml]
----
<cac:TenderingProcess>
    <cbc:Description languageID="ENG">A two stages procedure ...</cbc:Description>
    <cbc:Description languageID="FRA">Une procedure en deux étapes ...</cbc:Description>
    <!-- Interrupted Mark-Up -->
</cac:TenderingProcess>
----

[[procedureTypeSection]]
=== Procedure Type (BT-105)

This term refers to the type of procurement procedure (e.g. according to
the types given in the procurement Directives). It is marked for the
whole Procedure with the "_cbc:ProcedureCode_" element. Allowed values are
reported in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/procurement-procedure-type[procurement-procedure-type]
codelist.

For procedures types codified with the "oth-mult" or "oth-single" values
(i.e. PIN CFC social & CN social), the procedure features (BT-88) must
also be specified.

For a competitive dialog, the Procedure Type shall be marked:

[source,xml]
----
<cbc:ProcedureCode listName="procurement-procedure-type">comp-dial</cbc:ProcedureCode>
----

[[competitionTerminationSection]]
=== PIN Competition Termination (BT-756)

This indicator marks the end of a competition associated to a PIN used
as a call for competition (or a specific Lot) and no further contracts,
besides those published in this notice, will be awarded. This field can
be used even if no contracts are awarded in the contract award notice
and is marked as follows:

[source,xml]
----
<cbc:TerminatedIndicator>true</cbc:TerminatedIndicator>
----

It should apply at the Procedure or Lot level depending on the concerned
object. Applied at the Procedure level, it does not however mark the end
of notice publications since Change notices and Contract Modifications
could still be created.

[[allLotsSection]]
=== Lots All Required (BT-763)

This term is used to specify that any tenderer must submit tenders for
all Lots. This element shall be used when and only when tendering for
all existing Lots is mandatory. For this, the
"_cbc:PartPresentationCode_" element is used with a single possible
value: "_all_"

[source,xml]
----
<cbc:PartPresentationCode listName="tenderlot-presentation">all</cbc:PartPresentationCode>
----

[[eSubmissionSection]]
=== SubmissionElectronic (BT-17)

This term is used to specify the electronic transmission requirement for
document submission (tenders, request to participate and expression of
interest).

This information shall be reported per Lot. Allowed values are listed in
the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission[permission]
codelist.

[source,xml]
----
<cbc:SubmissionMethodCode listName="esubmission">allowed</cbc:SubmissionMethodCode>
----

The presence of the appropriate information for electronic (e.g. URL,
email address ...) and non-electronic (e.g. postal address) transmissions
is driven by the specified value.

[[successiveReductionSection]]
=== Successive Reduction Indicator (Procedure) (BT-52)

This term is an indicator used to specify per Lot whether the procedure
is a multi-stages one or not; At each stage, participants may be
eliminated.

Only two values are possible, "true" and "false":

[source,xml]
----
<cbc:CandidateReductionConstraintIndicator>true</cbc:CandidateReductionConstraintIndicator>
----

[[GPASection]]
=== GPA Coverage (BT-115)

An indicator may be used to specify whether a procurement associated to
a Lot is covered by a Government Procurement Agreement or not.

[source,xml]
----
<cbc:GovernmentAgreementConstraintIndicator>true</cbc:GovernmentAgreementConstraintIndicator>
----

[[atypicalToolSection]]
=== Tool Atypical URL (BT-124)

When communication requires an atypical tool or device, the URL to
access this tool or device shall be marked:

[source,xml]
----
<cbc:AccessToolsURI>https://my-atypical-tool.com/</cbc:AccessToolsURI>
----

[[tendersDeadlineSection]]
=== Deadline Receipt Tenders (BT-131)

For a given Lot, the deadline for tender receipt is marked by specifying
date and time:

[source,xml]
----
<cac:TenderSubmissionDeadlinePeriod>
    <cbc:EndDate>2019-11-30+01:00</cbc:EndDate>
    <cbc:EndTime>12:00:00+01:00</cbc:EndTime>
</cac:TenderSubmissionDeadlinePeriod>
----

[[tenderInvitationSection]]
=== Dispatch Invitation Tender (BT-130)

For procedures involving 2 or more stages, the estimated date for the
dispatching of the invitation to tender is encoded using a
"cac:InvitationSubmissionPeriod" component:

[source,xml]
----
<cac:InvitationSubmissionPeriod>
    <cbc:StartDate>2019-11-15+01:00</cbc:StartDate>
</cac:InvitationSubmissionPeriod>
----

[[interestInvitationSection]]
=== Dispatch Invitation Interest (BT-631)

For PIN call for competition notices, the estimated date of dispatch of
the invitations to confirm interest is encoded using
"_cac:ParticipationInvitationPeriod_":

[source,xml]
----
<cac:ParticipationInvitationPeriod>
    <cbc:StartDate>2019-11-15+01:00</cbc:StartDate>
</cac:ParticipationInvitationPeriod>
----

[[requestDeadlineSection]]
=== Deadline Receipt Requests (BT-1311)

For a given Lot, the deadline for receipt of requests to participate is
expressed with components of the
"cac:ParticipationRequestReceptionPeriod" element:

[source,xml]
----
<cac:ParticipationRequestReceptionPeriod>
    <cbc:EndDate>2019-11-25+01:00</cbc:EndDate>
    <cbc:EndTime>12:00:00+01:00</cbc:EndTime>
</cac:ParticipationRequestReceptionPeriod>
----

[[additionalInfoDeadlineSection]]
=== Additional Information Deadline (BT-13)

For a given Lot, or Group of Lots, the deadline to request for
additional information is encoded as follows:

[source,xml]
----
<cac:AdditionalInformationRequestPeriod>
    <cbc:EndDate>2019-11-08+01:00</cbc:EndDate>
    <cbc:EndTime>18:00:00+01:00</cbc:EndTime>
</cac:AdditionalInformationRequestPeriod>
----

[[previousPlanningSection]]
=== Previous Planning & Planning Part Identifiers (BT-125, BT-1251)

Identification of a Planning notice related to this notice is done using
its notice identifier (UUID) concatenated with the associated version
identifier (2 digits) in the form <UUUID>-<vv>. Another option is to
refer to the Notice Publication ID (XXXXXX-YYYY). Both may be differentiated
with the schemeName: "notice-id-ref" and "ojs-notice-id" respectively.

Parts of the referenced Planning notice are individually identified
using multiple occurrences of the element
"_cbc:ReferencedDocumentInternalAddress_". The ID for the reference to
the Part shall following the scheme ID reported in <<IDsReferencesSection>>, namely
"PAR-XXXX".

[source,xml]
----
<cac:NoticeDocumentReference>
    <cbc:ID schemeName="notice-id-ref">123e4567-e89b-12d3-a456-426614174000-06</cbc:ID>
    <cbc:ReferencedDocumentInternalAddress>PAR-0001</cbc:ReferencedDocumentInternalAddress>
    <cbc:ReferencedDocumentInternalAddress>PAR-0003</cbc:ReferencedDocumentInternalAddress>
</cac:NoticeDocumentReference>
----

Considerations:

* Reference to Parts shall be encoded only when the referred
Planning notice is of type "PIN only";

* Since a Lot may be defined based on multiple Parts, and Parts
may belong to different "PIN only" notices,
"cac:NoticeDocumentReference" and
"cbc:ReferencedDocumentInternal-Address" are repeatable;

* Two "cac:NoticeDocumentReference" elements with the same parent (i.e. leading by combination to the definition of a given Lot) shall have different notice identifiersfootnote:[It is not enough to have a different version number, the UUID part of the notice identification should differ. For a given Notice, since the reference to Parts is repeatable, all Parts needed are identified together without referring multiple times to the same notice.];

* When the referenced notice is of any other type, since Lots
shall neither be added/suppressed/redefined, only notice identifier &
version should be reported;

* For a given procurement Procedure, the reference to a previous
notice containing Lots shall be reported in the "cac:TenderingProcess"
element of the notice; while, when referring to Parts of a previous
notice, the reference shall be encoded in the "cac:TenderingProcess" of
the Lot the Parts are contributing to define.

[[nonelectronicSection]]
=== Submission Nonelectronic Justification (BT-19) & Description (BT-745)

For a Lot, when the electronic submission is prohibited (i.e. the value
associated to BT-17 equals "not-allowed"), BT-19 and BT-745 must be
specified:

[source,xml]
----
<cac:ProcessJustification>
    <cbc:ProcessReasonCode listName="no-esubmission-justification">phy-mod</cbc:ProcessReasonCode>
    <cbc:Description languageID="ENG">Tenders shall be sent per registered letter ...</cbc:Description>
    <cbc:Description languageID="FRA">Les offres doivent être transmises par lettre ...</cbc:Description>
</cac:ProcessJustification>
----

Possible values for the "No eSubmission Justification"
are listed in the https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/communication-justification[communication-justification]
codelist.

[[acceleratedProcedureSection]]
=== Procedure Accelerated (BT-106) and Justification (BT-1351)

When the Procedure is accelerated the "true" code shall be used, otherwise
the "false" code shall apply. For an accelerated Procedure, the
justification is encoded with the ProcessReason element:

[source,xml]
----
<cac:ProcessJustification>
    <cbc:ProcessReasonCode listName="accelerated-procedure">true</cbc:ProcessReasonCode>
    <cbc:ProcessReason languageID="ENG">The urgent aspect of ...</cbc:ProcessReason>
    <cbc:ProcessReason languageID="FRA">Le caractère urgent de ...</cbc:ProcessReason>
</cac:ProcessJustification>
----

[[directAwardSection]]
=== Direct Award Justification (BT-135, BT-136, BT-1252) 

When the Procedure Type is a Direct Award, then the justification is
encoded with the "cbc:ProcessReasonCode" element. The
"cbc:ProcessReason" element may be used to provide further information
as text when required and "cbc:Description" may be used to refer to the previous
procedure (using its UUID) that justified the Direct Award:

[source,xml]
----
<cac:ProcessJustification>
    <cbc:ProcessReasonCode listName="direct-award-justification">ecom-excl</cbc:ProcessReasonCode>
    <cbc:ProcessReason languageID="ENG">Direct award is justified ...</cbc:ProcessReason>
    <cbc:ProcessReason languageID="FRA">L'attribution ...</cbc:ProcessReason>
    <cbc:Description>123e4567-e89b-12d3-a456-426614174000</cbc:Description>
</cac:ProcessJustification>
----

The list to be used for the ProcessReasonCode is the
https://op.europa.eu/web/eu-vocabularies/dataset/-/resource/dataset/direct-award-justification[direct-award-justification],
of which the use of codes is context dependent as shown in <<directAwardJustificationCodeContextUseTable>>.

[[directAwardJustificationCodeContextUseTable]]
.Direct Award Justification code context use
[cols="<.^h,^.^,^.^,^.^,^.^,^.^,^.^,^.^,^.^,^.^",]
[%noheader]
|===
.2+^|*Code* 4+|*V E A T* 4+|*C A N* .2+|*MOVE*
|_D23_ |_D24_ |_D25_ |_D81_ |_D23_ |_D24_ |_D25_ |_D81_
|dir81-annexii | | | | | | | |X |
|unsuitable | | | | |X |X |X |X |
|irregular | | | | | | | |X |
|resd | | | | | |X |X |X |
|rd | | | | | | | |X |
|technical | | | | |X |X |X |X |
|artistic | | | | |X |X |X | |
|exclusive | | | | |X |X |X | |
|other-exclusive | | | | |X | | | |
|crisis | | | | | | | |X |
|urgency | | | | | | | |X |
|existing | | | | |X |X |X | |
|repetition | | | | | |X |X |X |
|contest | | | | | |X |X | |
|commodity | | | | | |X |X |X |
|closure | | | | | |X |X |X |
|liquidator | | | | | |X |X |X |
|bargain | | | | | | |X | |
|dir81-transport | | | | | | | |X |
|additional | | | |X | | | |X |
|below-thres |X |X |X |X | | | | |X
|ecom-excl |X |X | | | | | | |
|int-rules |X |X |X |X | | | | |
|serv-excl |X |X |X |X | | | | |
|sc-right |X |X |X | | | | | |
|in-house |X |X |X | | | | | |
|defse-excl |X |X |X |X | | | | |
|dir24-list | |X | | | | | | |
|rl-third | | |X | | | | | |
|other-activity |X | |X | | | | | |
|water-purch |X | |X | | | | | |
|energy-supply | | |X | | | | | |
|spe-arrang |X | |X | | | | | |
|tra-ser |X | | | | | | | |
|non-p-int | |X |X |X | | | | |
|non-buyer-aw | |X |X |X | | | | |
|not-wss | |X |X |X | | | | |
|non-contr |X |X | | | | | | |
|int-oper | | | | | | | | |X
|below-thres-sme | | | | | | | | |X
|rail | | | | | | | | |X
|===

[[maxCandidatesSection]]
=== Maximum Candidates Indicator (BT-661), Maximum & Minimum Candidates (Procedure) (BT-50)

Respectively:

* the existence of a maximum number of candidates,

* this maximum number of candidates, and

* the minimum number of candidates to be invited for the second
stage,

are marked as follows:

[source,xml]
----
<cac:EconomicOperatorShortList>
    <cbc:LimitationDescription>true</cbc:LimitationDescription>
    <cbc:MaximumQuantity>10</cbc:MaximumQuantity>
    <cbc:MinimumQuantity>3</cbc:MinimumQuantity>
</cac:EconomicOperatorShortList>
----

It shall not be confused with the construction built in Tendering Terms
using the same element "_cac:EconomicOperatorShortList_". Here it
references a process establishing a short list, while in the Tendering
Terms, it references an existing list of already screened tenderers.

"_cbc:LimitationDescription_":

* is used as an indicator (only possible values are "true" &
"false"), the languageID attribute shall not be used;

* shall not occur more than once in the same parent;

* must be given and set to "true", when "_cbc:MaximumQuantity_"
is specified.

"_cbc:MaximumQuantity_" and "_cbc:MinimumQuantity_":

* shall be integers with the first one greater or equal to the
second one, when both are specified;

[[openingEventSection]]
=== Opening event

For a given Lot, the Public Opening Date (BT-132), Description (BT-134)
and Place (BT-133) are encoded as follows:

[source,xml]
----
<cac:OpenTenderEvent>
    <cbc:OccurrenceDate>2019-11-05+01:00</cbc:OccurrenceDate>
    <cbc:OccurrenceTime>14:00:00+01:00</cbc:OccurrenceTime>
    <cbc:Description languageID="ENG">Any tenderer may attend ...</cbc:Description>
    <cbc:Description languageID="FRA">Tout soumissionaire peut participer ...</cbc:Description>
    <cac:OccurenceLocation>
        <cbc:Description languageID="ENG">online at URL https://event-on-line.org/d22f65 ...</cbc:Description>
        <cbc:Description languageID="FRA">en ligne à l'URL https://event-on-line.org/d22f65 ...</cbc:Description>
    </cac:OccurenceLocation>
</cac:OpenTenderEvent>
----

[[auctionTermsSection]]
=== Auction Terms

The use, for a given Lot, or Group of Lots, of an electronic auction
system (BT-767) is specified with an indicator. When the value is
"true", Description (BT-122) and URL (BT-123) should be specified.

[source,xml]
----
<cac:AuctionTerms>
    <cbc:AuctionConstraintIndicator>true</cbc:AuctionConstraintIndicator>
    <cbc:Description languageID="ENG">The online auction solution ...</cbc:Description>
    <cbc:Description languageID="FRA">La solution d'enchères en ligne ...</cbc:Description>
    <cbc:AuctionURI>https://my-online-eauction.eu/</cbc:AuctionURI>
</cac:AuctionTerms>
----

[[frameworkAgreementSection]]
=== Framework Agreement

When, for a lot (or Group of Lots), no Framework Agreement (FA) is used,
then, when the information is expected, it may be reported as follows:

[source,xml]
----
<cac:ContractingSystem>
    <cbc:ContractingSystemTypeCode listName="framework-agreement">none</cbc:ContractingSystemTypeCode>
</cac:ContractingSystem>
----

When, for a Lot (or Group of Lots), a framework agreement (FA) is
foreseen (PIN & CN) for the execution:

* the type of FA along with the possible maximum number of participants (BT-113)footnote:[Its specification implies a "true" value for BT-778.],

* the duration justification (BT-109)footnote:[This information is to be provided only when the duration exceeds 4 years for general directive (Dir. 24), 7 years for defence (Dir. 81) and 8 years for the sectoral directive (Dir. 25).],

* the Group Framework Estimated Maximum Value (BT-157)footnote:[Evaluation at start of the call for competition, only in the context of a group when this group has a foreseen framework agreement.], and

* the buyers categories (BT-111)

should be specified.

* The maximum number of participants shall be an integer;

* the duration justification shall be of type text,

* the estimated framework maximum value for the Group of Lots
shall be a monetary value,

* the buyer categories shall be of type text; and

* the framework agreement type shall be one of the values listed
in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/framework-agreement[framework-agreement]
codelist.

[source,xml]
----
<cac:FrameworkAgreement>
    <cbc:MaximumOperatorQuantity>50</cbc:MaximumOperatorQuantity>
    <cbc:Justification languageID="ENG">The exceptional duration of ...</cbc:Justification>
    <cbc:Justification languageID="FRA">La durée exceptionnelle de ...</cbc:Justification>
    <cbc:EstimatedMaximumValueAmount currencyID="EUR">200000</cbc:EstimatedMaximumValueAmount>
    <cac:SubsequentProcessTenderRequirement>
        <cbc:Name>buyer-categories</cbc:Name>
        <cbc:Description languageID="ENG">Offices of the "greater region" ...</cbc:Description>
        <cbc:Description languageID="FRA">Bureaux de la "Grande région" ...</cbc:Description>
    </cac:SubsequentProcessTenderRequirement>
</cac:FrameworkAgreement>
<cac:ContractingSystem>
    <cbc:ContractingSystemTypeCode listName="framework-agreement">fa-wo-rc</cbc:ContractingSystemTypeCode>
</cac:ContractingSystem>
----

For a CAN, when a Framework Agreement is involved, only the following
information is expected at the level of the Lot/Group of Lots
definition:

* Group Framework Estimated Maximum Value (BT-157),

* The framework buyer categories (BT-111), and

* The Framework Agreement type (BT-765).

[source,xml]
----
<cac:FrameworkAgreement>
    <cbc:EstimatedMaximumValueAmount currencyID="EUR">200000</cbc:EstimatedMaximumValueAmount>
    <cac:SubsequentProcessTenderRequirement>
        <cbc:Name>buyer-categories</cbc:Name>
        <cbc:Description languageID="ENG">Offices of the "greater region" ...</cbc:Description>
        <cbc:Description languageID="FRA">Bureaux de la "Grande région" ...</cbc:Description>
    </cac:SubsequentProcessTenderRequirement>
</cac:FrameworkAgreement>
<cac:ContractingSystem>
    <cbc:ContractingSystemTypeCode listName="framework-agreement">fa-wo-rc</cbc:ContractingSystemTypeCode>
</cac:ContractingSystem>
----

[[DPSSection]]
=== Dynamic Purchasing System (BT-766)

The existence of a Dynamic Purchasing System (DPS) and its use is
specified with the "_cbc:ContractingSystemTypeCode_" element with a
value from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/dps-usage[dps-usage]
codelist; It shall be marked:

[source,xml]
----
<cac:ContractingSystem>
    <cbc:ContractingSystemTypeCode listName="dps-usage">dps-nlist</cbc:ContractingSystemTypeCode>
</cac:ContractingSystem>
----

== Procurement Project

[[procurementProjectRelatedInformationTable]]
.Procurement project related information
[width="100%",cols="<.^10%,^.^5%,^.^5%,^.^5%,^.^5%,^.^5%,^.^5%,^.^5%,^.^5%,^.^5%,<.^45%",]
[%noheader]
|===
.2+^|*eForms BT* .2+|*Details* .2+|*Procedure* 3+|*PIN* 2+|*CN* 2+|*CAN* .2+^|*XSD
element*
|G.Lot |Lot |Part |G.Lot |Lot |G.Lot |Lot

11+^|*Identification (+++*+++)*

|*Internal Identifier (BT-22)* |xref:objectSection[xrefstyle=short] |*1* |*1* |*1* |*1* |*1* |*1*
|*1* |*1* a|
[source,xpath,subs=attributes]
----
cbc:ID
----

|*Title (BT-21)* |xref:objectSection[xrefstyle=short] |*1* |*?* |*1* |*1* |*?* |*1* |*?* |*1*
a|
[source,xpath,subs=attributes]
----
cbc:Name
----

|*Description (BT-24)* |xref:objectSection[xrefstyle=short] |*1* |*?* |*1* |*1* |*?* |*1* |*?*
|*1* a|
[source,xpath,subs=attributes]
----
cbc:Description
----


11+^|*Nature (+++*+++)* 

|*Main Nature (BT-23)* |xref:natureSection[xrefstyle=short] |*1* |-- |*1* |*1* |-- |*1* |--
|*1* a|
[source,xpath,subs=attributes]
----
cbc:ProcurementTypeCode
----

|*Additional Nature (different from Main) (BT-531)* |xref:natureSection[xrefstyle=short] |*** |--
|*** |*** |-- |*** |-- |*** a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode
----


11+^|*Strategic Procurement (+++*+++)* 

|*Strategic Procurement (BT-06)* |xref:strategicProcurementSection[xrefstyle=short] |-- |-- |*** |-- |-- |*** |-- |*** 
a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode{zwsp}[@listName='strategic-procurement']
----

|*Strategic Procurement Description (BT-777)* |xref:strategicProcurementSection[xrefstyle=short] |-- |-- |*** |-- |-- |*** |-- |*** 
a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementType
----


11+^|*Procurement type (+++*+++)*

|*Green Procurement (BT-774)* |xref:strategicProcurementSection[xrefstyle=short] |-- |-- |*** |-- |-- |*** |-- |*** 
a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode{zwsp}[@listName='environmental-impact']
----

|*Social Procurement (BT-775)* |xref:strategicProcurementSection[xrefstyle=short] |-- |-- |*** |-- |-- |*** |-- |*** 
a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode{zwsp}[@listName='social-procurement']
----

|*Innovative Procurement (BT-776)* |xref:strategicProcurementSection[xrefstyle=short] |-- |-- |*** |-- |-- |*** |-- |*** 
a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode{zwsp}[@listName='innovative-acquisition']
----



11+^|*Accessibility* 

|*Accessibility Justification (BT-755)* |xref:accessibilitySection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementType
----

|*Accessibility (BT-754)* |xref:accessibilitySection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ProcurementAdditionalType{zwsp}/cbc:ProcurementTypeCode
----


11+^|*Quantity (+++*+++)* 

|*Quantity (BT-25)* |xref:quantitySection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
cbc:EstimatedOverallContractQuantity
----

|*Unit (BT-625)* |xref:quantitySection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
cbc:EstimatedOverallContractQuantity{zwsp}/@unitCode
----

11+^|*Aggregated amounts & additional information* 

|*Suitable for SMEs (BT-726)* |xref:suitableSMESection[xrefstyle=short] |-- h|? h|? h|? h|? h|? |-- |-- a|
[source,xpath,subs=attributes]
----
cbc:SMESuitableIndicator
----

|*Additional Information (BT-300) (**)* |xref:additionalInfoSection[xrefstyle=short] h|? h|? h|? h|? h|? h|? h|? h|? a|
[source,xpath,subs=attributes]
----
cbc:Note
----

|*Estimated Value (BT-27)* |xref:estimatedValueSection[xrefstyle=short] h|? h|? h|? h|? h|? h|? h|? h|? a|
[source,xpath,subs=attributes]
----
cac:RequestedTenderTotal{zwsp}/cbc:EstimatedOverallContractAmount
----
and?
[source,xpath,subs=attributes]
----
@currencyID
----

11+^|*Classification (+++*+++)* 

|*Classification Type (e.g. CPV) (BT-26)* |xref:classificationSection[xrefstyle=short] |*1* |-- |*1* |*1*
|-- |*1* |-- |*1* a|
[source,xpath,subs=attributes]
----
cac:MainCommodityClassification{zwsp}/cbc:ItemClassificationCode{zwsp}/@listName
----
Or
[source,xpath,subs=attributes]
----
cac:AdditionalCommodityClassification{zwsp}/cbc:ItemClassificationCode{zwsp}/@listName
----

|*Main Classification Code (BT-262)* |xref:classificationSection[xrefstyle=short] |*1* |-- |*1* |*1*
|-- |*1* |-- |*1* 
a|
[source,xpath,subs=attributes]
----
cac:MainCommodityClassification{zwsp}/cbc:ItemClassificationCode
----

|*Additional Classification Code (BT-263)* |xref:classificationSection[xrefstyle=short] |*** |-- |***
|*** |-- |*** |-- |***
a|
[source,xpath,subs=attributes]
----
cac:AdditionalCommodityClassification{zwsp}/cbc:ItemClassificationCode
----


11+^|*Place of Performance (+++*+++)* 

|*Place of Performance Additional Information (BT-728)* |xref:performancePlaceSection[xrefstyle=short] h|?
|-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cbc:Description
----

|*Place Performance City (BT-5131)* a| xref:performancePlaceSection[xrefstyle=short]
h|?|-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:CityName
----

|*Place Performance Post Code (BT-5121)* |xref:performancePlaceSection[xrefstyle=short] h|?
|-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:PostalZone
----

|*Place Performance Country Subdivision (BT-5071)* |xref:performancePlaceSection[xrefstyle=short] h|?
|-- h|? h|? |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:CountrySubentityCode
----

|*Place Performance Services Other (BT-727)* |xref:performancePlaceSection[xrefstyle=short] h|?
|-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:Region
----
use of codelist "Place Performance Services Other"

|*Place Performance Street (BT-5101)* |xref:performancePlaceSection[xrefstyle=short] h|?
|-- h|? h|? |-- h|? |-- h|? a|
First line:

[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:StreetName
----
Second line:

[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cbc:AdditionalStreetName
----
Third line:
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cac:AddressLine{zwsp}/cbc:Line
----

|*Place Performance Country Code (BT-5141)* |xref:performancePlaceSection[xrefstyle=short] h|? |-- h|? h|? |-- h|? |-- h|? 
a|
[source,xpath,subs=attributes]
----
cac:RealizedLocation{zwsp}/cac:Address{zwsp}/cac:Country{zwsp}/cbc:IdentificationCode
----


11+^|*Planned period (+++*+++)* 

|*Duration Start Date (BT-536)* |xref:plannedPeriodSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:PlannedPeriod{zwsp}/cbc:StartDate
----

|*Duration End Date (BT-537)* |xref:plannedPeriodSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:PlannedPeriod{zwsp}/cbc:EndDate
----

|*Duration Period (BT-36)* |xref:plannedPeriodSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:PlannedPeriod{zwsp}/cbc:DurationMeasure
----
AND
[source,xpath,subs=attributes]
----
@unitCode
----

|*Duration Other (BT-538)* |xref:plannedPeriodSection[xrefstyle=short] |-- |-- h|? h|? |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:PlannedPeriod{zwsp}/cbc:DescriptionCode
----
with value "unlimited"

AND
[source,xpath,subs=attributes]
----
@listName="Duration"
----

11+^|*Contract extensions (+++*+++)*

|*Options Description (BT-54)* |xref:extensionsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ContractExtension{zwsp}/cbc:OptionsDescription
----

|*Renewal maximum (BT-58)* |xref:extensionsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ContractExtension{zwsp}/cbc:MaximumNumberNumeric
----

|*Renewal Description (BT-57)* |xref:extensionsSection[xrefstyle=short] |-- |-- h|? |-- |-- h|? |-- h|? a|
[source,xpath,subs=attributes]
----
cac:ContractExtension{zwsp}/cac:Renewal{zwsp}/cac:Period{zwsp}/cbc:Description
----

11+a|
*Contexts:*

(+++*+++)

[source,xpath,subs=attributes]
----
/*/cac:ProcurementProject{zwsp}/

/*/cac:ProcurementProjectLot{zwsp}/cac:ProcurementProject{zwsp}/
----

|===

[[objectSection]]
=== Internal ID (BT-22), Title (BT-21) & Description (BT-24)

For the Procedure, the Parts, the Lots and the Group of Lots, a
contracting authority may specify an internal identifier. There is no
specific restriction regarding its structure, and any construct is
possible.

While no specific rules apply, the contracting authority should ensure
that, for all Procedures it advertises using notices, the internal
identifier would be unique. Otherwise, for a given contracting
authority, having two different Procedures sharing the same internal ID,
would make it impossible to list notices belonging to one or the other
Procedure, based on the Buyer's and Internal Procedure Identifiers only.

Internal Identifier shall be marked:

[source,xml]
----
<cbc:ID schemeName="InternalID">PROC/2020/0024-ABC-FGHI</cbc:ID>
----

Title and description may also be specified for the procedure, Parts,
Groups of Lots and Lots; title and description are language dependant.

The corresponding elements, of type text, shall have their associated
"languageID" attribute value specified using a
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/language[language]
code.

For each linguistic version, these shall exist only once.

[source,xml]
----
<cbc:Name languageID="ENG">Computer Network extension</cbc:Name>
<cbc:Name languageID="FRA">Extension du réseau informatique</cbc:Name>
<cbc:Description languageID="ENG">Procedure for the procurement of ...</cbc:Description>
<cbc:Description languageID="FRA">Procédure pour la fourniture de ...</cbc:Description>
----

[[procurementTypeSection]]
=== Main & Additional Nature (BT-23, BT-531), Strategic Procurement (BT-06, BT-774, BT-775, BT-776, BT-777), and Accessibility (BT-754, BT-755)

Main Nature (BT-23) is specified using the element 
"_cbc:ProcurementTypeCode_" directly within the "_cac:ProcurementProject​_"
 element. All the other business terms  use the 
 "_cbc:ProcurementTypeCode_" element within a 
"_cac:ProcurementAdditionalType_" element. This may also contain a 
multilingual text description in a "_cbc:ProcurementType_" element.

[[natureSection]]
==== Main & Additional Nature (BT-23, BT-531)

The possible values are listed in the https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/contract-nature[contract-nature] codelistfootnote:[The use of the "combined" code is restricted to "TEDXML" and is not a valid one for "eForms".].

The "Additional Nature" may use one of the 3 values, however it shall be 
different from "Main Nature" and from the other "Additional Nature", when it
exists.

Considerations:

* There shall be one and only one "Main Nature" for a Procedure,
Lot, or Part;

* Given that :

** there are 3 distinct nature codes usable to qualify the Main and
Additional Natures,

** Additional Natures must differ from the Main Nature,

** Additional Natures must not be duplicated,

then, for a given Procedure, Lot or Part, there may be up-to two
Additional Natures only.

[[strategicProcurementSection]]
==== Strategic Procurement (BT-06, BT-774, BT-775, BT-776, BT-777)

For a given Lot, strategic projects are identified using the "listName"
attribute of the "_cbc:ProcurementTypeCode_" element. The value of the
listName attribute shall refer to the appropriate codelist
(https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/strategic-procurement[strategic-procurement]
for strategic procurement BT-06,
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/environmental-impact[environmental-impact]
for Green Procurement BT-774,
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/innovative-acquisition[innovative-acquisition]
for Innovative Procurement BT-776,
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/social-objective[social-objective]
for Social Procurement BT-775).

Multiple "_cac:ProcurementAdditionalType_" elements may be used to
highlight the different aspects of the procurement (e.g. for an
innovative procurement aiming at reducing environmental impacts as
illustrated in the example below).

The Strategic Procurement description (BT-777) shall be marked 
using the "_cbc:ProcurementType_" element.

[[accessibilitySection]]
==== Accessibility (BT-754, BT-755)

Whether accessibility criteria for persons with disabilities are included
(BT-754) for a lot may be indicated with a "_cbc:ProcurementTypeCode_" element, with the "listName" 
attribute set to "accessibility", and a value from the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/accessibility[accessibility]
codelist. BT-754 is not repeatable, as the values in the codelist are 
mutually exclusive. If the procurement is intended for natural persons, 
but no accessibility criteria are given, then the value "n-inc-just" shall be used, 
and the Accessibility Justification (BT-755) shall be given using the 
"_cbc:ProcurementType_" element. 

The below example illustrates the expression of one Main and two Additional 
Natures, two strategic projects, and a code and justification for the 
absence of accessibility criteria.

[source,xml]
----
<cbc:ProcurementTypeCode listName="contract-nature">works</cbc:ProcurementTypeCode>
<!-- Interrupted Mark-up -->
<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="contract-nature">services</cbc:ProcurementTypeCode>
</cac:ProcurementAdditionalType>
<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="contract-nature">supplies</cbc:ProcurementTypeCode>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="strategic-procurement">inn-pur</cbc:ProcurementTypeCode>
    <cbc:ProcurementType languageID="ENG">This is a strategic procurement involving the innovative use of ...</cbc:ProcurementType>
    <cbc:ProcurementType languageID="FRA">Il s'agit d'une fourniture stratégique impliquant l'utilisation innovante de...</cbc:ProcurementType>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="strategic-procurement">env-imp</cbc:ProcurementTypeCode>
    <cbc:ProcurementType languageID="ENG">Compliance with EMAS ...</cbc:ProcurementType>
    <cbc:ProcurementType languageID="FRA">Conformité à l'EMAS ...</cbc:ProcurementType>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="innovative-acquisition">mar-nov</cbc:ProcurementTypeCode>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="innovative-acquisition">buy-eff</cbc:ProcurementTypeCode>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="environmental-impact">emas-com</cbc:ProcurementTypeCode>
</cac:ProcurementAdditionalType>

<cac:ProcurementAdditionalType>
    <cbc:ProcurementTypeCode listName="accessibility">n-inc-just</cbc:ProcurementTypeCode>
    <cbc:ProcurementType languageID="ENG">Accessibility criteria are not included ...</cbc:ProcurementType>
    <cbc:ProcurementType languageID="FRA">Les critères d'accessibilité ne sont pas inclus ...</cbc:ProcurementType>
</cac:ProcurementAdditionalType>
----

[[quantitySection]]
=== Quantity & Unit (BT-25, BT-625)

The list of possible units is in the
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/measurement-unit[measurement-unit]
codelist.

Quantity is any numeric value representing the quantity in a given unitfootnote:[Monetary value units are not to be expected here, since dedicated terms have also been defined (cf. <<estimatedValueSection>>, <<classificationSection>>).].

A procurement dealing with 45,000 tonnes of supplies shall be marked:

[source,xml]
----
<cbc:EstimatedOverallContractQuantity unitCode="TNE">45000</cbc:EstimatedOverallContractQuantity>
----

[[suitableSMESection]]
=== Suitable for SMEs (BT-726)

For PIN and CN, the contracting authority may specify that a Group of
lots, Lot, or Part, is suitable for SMEs by using the
"_cbc:SMESuitableIndicator_" in the "_cac:ProcurementProject_" element of
the corresponding Group of Lots/Lot/Part, with a value of "true".
The contracting authority may explicitly specify that a Group of
lots, Lot, or Part, is not suitable for SMEs by using a value of "false".

[source,xml]
----
<cbc:SMESuitableIndicator>true</cbc:SMESuitableIndicator>
----

[[additionalInfoSection]]
=== Additional information

For the Procedure, Part, Lot, or Group of Lots, any additional
information not reported elsewhere may be marked using the "_cbc:Note_"
child of the appropriate "_cac:ProcurementProject_"element.

[source,xml]
----
<cbc:Note languageID="ENG">For the current procedure ...</cbc:Note>
<cbc:Note languageID="FRA">Pour la procedure courante ...</cbc:Note>
----

[[estimatedValueSection]]
=== Estimated Value (BT-27)

The Estimated Value is marked using the
"_cbc:EstimatedOverallContractAmount_" and represents the aggregated
amount of all the individual components that constitute the current
notice, Group of Lots, Lot or Part. Currency and amount shall be
specified. Possible "currencyID" values are in the codelist
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/currency[currency].

The amount is a rough estimation by the contracting authority at
launch of the Call for Competition (or even earlier). When the
estimation was possible (except for "PIN profile" notices), the value
may be specified.

[source,xml]
----
<cac:RequestedTenderTotal>
    <cbc:EstimatedOverallContractAmount currencyID="EUR">250000</cbc:EstimatedOverallContractAmount>
</cac:RequestedTenderTotal>
----

[[classificationSection]]
=== Classification Type (BT-26), Main & Additional Classification Codes (BT-262, BT-263)

These business terms are used to designate the classification system
along with the main and the additional commodities classifications.

The used classification (Classification Type -- BT-26) is specified using
the listName attribute of the _"cbc:ItemClassificationCode_".

The main commodity is the one representing the highest value fraction.
Additional commodities are other commodities belonging to the same
Lot/Part or Procedure and which, taken individually and compared to the
main commodity, represent a lower portion of the overall lot/group
value.

Classification is currently only based on the main "_Common Procurement Vocabulary_" codes
(https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/cpv[CPV]) and "_Supplementary CPV_" are not implemented for eForms.

Other classification systems could later
be usedfootnote:[ATC is another example mentioned in a discussion on BT-26.].

For illustration purpose, we have reported below, a typical mark-up
based on different classifications:

* the CPV, and

* a hypothetical classification ABC with subsidiary codes (subsidiary codes appear in extensions of the
major classification of the commodity it refers to).

[source,xml]
----
<cac:MainCommodityClassification>
    <cbc:ItemClassificationCode listName="cpv">15311100</cbc:ItemClassificationCode>
</cac:MainCommodityClassification>
<cac:MainCommodityClassification>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <efext:EformsExtension>
                    <efac:SubsidiaryClassification>
                        <cbc:ItemClassificationCode listName="subsidiary-abc">AFGH</cbc:ItemClassificationCode>
                    </efac:SubsidiaryClassification>
                </efext:EformsExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <cbc:ItemClassificationCode listName="abc">XYZ/002</cbc:ItemClassificationCode>
</cac:MainCommodityClassification>
<cac:AdditionalCommodityClassification>
    <cbc:ItemClassificationCode listName="cpv">15311200</cbc:ItemClassificationCode>
</cac:AdditionalCommodityClassification>
<cac:AdditionalCommodityClassification>
    <cbc:ItemClassificationCode listName="cpv">15311500</cbc:ItemClassificationCode>
</cac:AdditionalCommodityClassification>
<cac:AdditionalCommodityClassification>
    <ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <efext:EformsExtension>
                    <efac:SubsidiaryClassification>
                        <cbc:ItemClassificationCode listName="subsidiary-abc">hdjd</cbc:ItemClassificationCode>
                    </efac:SubsidiaryClassification>
                    <efac:SubsidiaryClassification>
                        <cbc:ItemClassificationCode listName="subsidiary-abc">lelja</cbc:ItemClassificationCode>
                    </efac:SubsidiaryClassification>
                </efext:EformsExtension>
            </ext:ExtensionContent>
        </ext:UBLExtension>
    </ext:UBLExtensions>
    <cbc:ItemClassificationCode listName="abc">SCE/548</cbc:ItemClassificationCode>
</cac:AdditionalCommodityClassification>
----

[[performancePlaceSection]]
=== Place of performance (BG-708)

Since performance may take place at multiple locations, the place of
performance is repeatable.

This group may contain the following information:

* Additional Information (BT-728)

* City (BT-5131)

* Post Code (BT-5121)

* Country Subdivision (BT-5071)

* Services Other (as a codelist) (BT-727)

* Street (BT-5101)

* Code (BT-5141)

Use "_cbc:Region_" and a code from the codelist
https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/other-place-service[other-place-service]
to identify regions not covered with the _cbc:CountrySubentityCode_
(e.g. "country wide", "EEA wide", "anywhere")

[source,xml]
----
<!-- 1st Place of Performance -->
<cac:RealizedLocation>
    <cbc:Description languageID="ENG">The main location is ...</cbc:Description>
    <cbc:Description languageID="FRA">La localisation principale est ...</cbc:Description>
    <cac:Address>
        <cbc:StreetName>Main Street, 2</cbc:StreetName>
        <cbc:AdditionalStreetName>Building B1</cbc:AdditionalStreetName>
        <cbc:CityName>BigCity</cbc:CityName>
        <cbc:PostalZone>XY14 2LG</cbc:PostalZone>
        <cbc:CountrySubentityCode listName="nuts">UKG23</cbc:CountrySubentityCode>
        <cac:AddressLine>
            <cbc:Line>3rd floor</cbc:Line>
        </cac:AddressLine>
        <cac:Country>
            <cbc:IdentificationCode>GBR</cbc:IdentificationCode>
        </cac:Country>
    </cac:Address>
</cac:RealizedLocation>

<!-- 2nd place of performance -->
<cac:RealizedLocation>
    <cbc:Description languageID="ENG">Further realizations ...</cbc:Description>
    <cbc:Description languageID="FRA">Des réalisations complémentaires ...</cbc:Description>
    <cac:Address>
        <cbc:Region>anyw-eea</cbc:Region>
    </cac:Address>
</cac:RealizedLocation>
----

[[plannedPeriodSection]]
=== Procedure planned period

Multiple exclusive ways exist to report the Procurement duration:

* Specifying the duration,

* using start & end dates, or

* other means.

and the most suitable one shall be adopted.

* **+++Duration is "unlimited" or "unknown"+++** _(Duration
Other BT-538)_

The "_cbc:DescriptionCode_" element shall be used with the respective
code value "UNLIMITED" or "UNKNOWN". In this specific context, any other
value from the
https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/timeperiod[timeperiod]
codelist is prohibited

[source,xml]
----
<cac:PlannedPeriod>
    <cbc:DescriptionCode listName="timeperiod">UNLIMITED</cbc:DescriptionCode>
</cac:PlannedPeriod>
----

* **+++Duration is limited+++** (_Duration Period BT-36_)

The "_cbc:DurationMeasure_" element shall be used with the specification
of the unit (e.g. "days") and its total number to cover the whole
period. Unit of measure shall correspond to one of the duration units
defined in the
https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/timeperiod[timeperiod]
codelist.

[source,xml]
----
<cac:PlannedPeriod>
    <cbc:DurationMeasure unitCode="DAY">3</cbc:DurationMeasure>
</cac:PlannedPeriod>
----

* **+++Start & end dates are known+++** (_Duration Start Date
BT-536 & End Date BT-537_)

These dates shall be reported as follows:

[source,xml]
----
<cac:PlannedPeriod>
    <cbc:StartDate>2019-11-15+01:00</cbc:StartDate>
    <cbc:EndDate>2019-11-19+01:00</cbc:EndDate>
</cac:PlannedPeriod>
----

[[extensionsSection]]
=== Extensions & renewals

When Options exist (Options BT-53), they shall be described (Options
Description BT-54) using the "_cbc:OptionsDescription_" element.

For renewals, the maximum number of times a contract may be renewed
(Renewal Maximum BT-58) shall be marked with
"_cbc:MaximumNumberNumeric_", further information about renewal (Renewal
Description BT-57) shall be marked with "_cbc:Description_" as
illustrated below:

[source,xml]
----
<cac:ContractExtension>
    <cbc:OptionsDescription languageID="ENG">The buyer reserves the right to ...</cbc:OptionsDescription>
    <cbc:OptionsDescription languageID="FRA">L'acheteur se réserve le droit ...</cbc:OptionsDescription>
    <cbc:MaximumNumberNumeric>3</cbc:MaximumNumberNumeric>
    <cac:Renewal>
        <cac:Period>
            <cbc:Description languageID="ENG">The buyer reserves the right to ...</cbc:Description>
            <cbc:Description languageID="FRA">L'acheteur se réserve le droit ...</cbc:Description>
        </cac:Period>
    </cac:Renewal>
</cac:ContractExtension>
----

Considerations:

* cbc:MaximumNumberNumeric is mandatory for form subtypes 15
(Notice on the existence of a qualification system), 17 
and 18 (Contract, or concession, notice — standard regime, 
Directives 2014/25/EU and 2009/81/EC)

* cbc:MaximumNumberNumeric shall be a whole number (when no
extension is foreseen, the element shouldn't be used, except for
form subtypes 15, 17 and 18, where it should have the value 0)

* cbc:MaximumNumberNumeric refers to the number of possible
renewals; an encoded value of "3" involves an initial contract followed
by up to 3 renewals
