= References
[bibliography]

* [[[eFormsReg, R1]]] **Commission Implementing Regulation (EU) 2019/1780 of 23
September 2019 establishing standard forms for the publication of
notices in the field of public procurement and repealing Implementing
Regulation (EU) 2015/1986 (eForms) (Text with EEA relevance)** ,
_Official Journal of The European Union_, OJ L 272, Oct. 25^th^, 2019,
pp. 7 - 73, available at
[.MsoHyperlink]##http://data.europa.eu/eli/reg_impl/2019/1780/oj##,
accessed January 27^th,^ 2020.
* [[[oldForms, R2]]] **Commission Implementing Regulation (EU) 2015/1986 of 11
November 2015 establishing standard forms for the publication of notices
in the field of public procurement and repealing Implementing Regulation
(EU) No 842/2011**, _Official Journal of The European Union_, OJ L 296,
Nov. 12^th^, 2015, pp. 1 - 146, available at
http://data.europa.eu/eli/reg_impl/2015/1986/oj##,
accessed January 27^th,^ 2020
* [[[comComm,R3]]] **Communication From The Commission To The European Parliament,
The Council, The European Economic And Social Committee And The
Committee Of The Regions, Upgrading the Single Market: more
opportunities for people and business**, Oct. 28^th^, 2015, 23 p.,
available at
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52015DC0550[https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52015DC0550],
accessed January 27^th,^ 2020
* [[[nutsCodes,R4]]] **NUTS -- Nomenclature of territorial units for statistics,
**__Eurostat__,
https://ec.europa.eu/eurostat/web/nuts/background[https://ec.europa.eu/eurostat/web/nuts/background],
accessed April 16^th^, 2019.
* [[[reviewProc,R5]]] **Council Directive 89/665/EEC of 21 December 1989 on the
coordination of the laws, regulations and administrative provisions
relating to the application of review procedures to the award of public
supply and public works contracts**, _Official Journal of The European
Union_, OJ L 395 , Dec. 30^th^, 1989 pp. 33 -- 35, available at
[.MsoHyperlink]##http://data.europa.eu/eli/dir/1989/665/oj##, accessed
January 27^th,^ 2020
* [[[dir13,R6]]] **Council Directive 92/13/EEC of 25 February 1992 coordinating
the laws, regulations and administrative provisions relating to the
application of Community rules on the procurement procedures of entities
operating in the water, energy, transport and telecommunications
sectors**, _Official Journal of The European Union_, OJ L 076 , March
23^rd^, 1992, pp. 14 - 20, available at
[.MsoHyperlink]##http://data.europa.eu/eli/dir/1992/13/oj##, accessed
January 27^th^, 2020
* [[[dir23,R7]]] **Directive 2014/23/EU of the European Parliament and of the
Council of 26 February 2014 on the award of concession contracts, Text
with EEA relevance, **__Official Journal of The European Union__, OJ L
94, March 28^th^, 2014, pp. 1 - 64, accessible at
http://data.europa.eu/eli/dir/2014/23/oj[http://data.europa.eu/eli/dir/2014/23/oj],
accessed February 11^th^, 2020
* [[[dir24,R8]]] **Directive 2014/24/EU of the European Parliament and of the
Council of 26 February 2014 on public procurement and repealing
Directive 2004/18/EC, Text with EEA relevance, **__Official Journal of
The European Union__, OJ L 94, 28.3.2014, pp. 65 - 242, Available at
http://data.europa.eu/eli/dir/2014/24/oj[http://data.europa.eu/eli/dir/2014/24/oj],
accessed February 11^th^, 2020.
* [[[dir25,R9]]] **Directive 2014/25/EU of the European Parliament and of the
Council of 26 February 2014 on procurement by entities operating in the
water, energy, transport and postal services sectors and repealing
Directive 2004/17/EC, Text with EEA relevance. **__Official Journal of
The European Union__, OJ L 94, 28.3.2014, pp. 243 - 374, available at
http://data.europa.eu/eli/dir/2014/25/oj[http://data.europa.eu/eli/dir/2014/25/oj],
accessed February 11^th^, 2020.
* [[[dir81,R10]]] **Directive 2009/81/EC of the European Parliament and of the
Council of 13 July 2009 on the coordination of procedures for the award
of certain works contracts, supply contracts and service contracts by
contracting authorities or entities in the fields of defence and
security, and amending Directives 2004/17/EC and 2004/18/EC (Text with
EEA relevance),**__ Official Journal of The European Union__, OJ L 216,
20.8.2009, pp. 76 - 136, accessible at
http://data.europa.eu/eli/dir/2009/81/oj[http://data.europa.eu/eli/dir/2009/81/oj],
accessed February 11^th^, 2020.
* [[[eFormsImpl,R11]]] **eForms Policy Implementation Handbook**, _European
Commission, Directorate-General for Internal Market, Industry,
Entrepreneurship and SMEs,_ 2019, 108 p., available at
https://op.europa.eu/en/publication-detail/-/publication/73a78487-cc8b-11ea-adf7-01aa75ed71a1[https://op.europa.eu/en/publication-detail/-/publication/73a78487-cc8b-11ea-adf7-01aa75ed71a1],
accessed April 6^th^, 2021
