:xrefstyle: short

= Schemas

Three schemas will cater for the different categories of notices. <<noticeTypesAndTheirAssociatedSchemasTable>> provides the correspondence between notice categories and the schemas.

For Change notices, the required schema is the one of the notice subject
to changes (e.g. a _Change Notice_ for a change applied to an existing
_Contract Notice_ shall comply with the _ContractNotice_ schema).

[[noticeTypesAndTheirAssociatedSchemasTable]]
.Notice Types and their associated schemas
[width="100%",cols=".^34%,.^33%,.^33%",frame="all",grid="all"]
|===
^|*Notice category* ^|*Notice Type* ^|*Schema*

h|Prior Information / Periodic Indicative Notice a|
* PIN profile
* PIN only
* PIN time limit
* PIN CFC general
* PIN CFC social
* QS

|PriorInformationNotice

h|Contract Notice a|
* CN general
* CN social
* CN subco
* CN design

|ContractNotice

h|Direct Award Pre-notification Notice a|* CAN VEAT
.3+a|ContractAwardNotice

h|Contract Award Notice a|
* CAN general
* CAN social
* CAN design

h|Contract Modification Notice a|* Contract modification

h|Change Notice a|* Change notice | _Any of the 3_
|===

The schemas are built using elements from different namespaces (some
defined by UBL, others created for the purpose of eForms) and a version
number will be used to distinguish different releases. Information on
namespaces and schema versioning is provided below.

== Namespaces

The namespaces used in the eForms schemas are described below in Table
3.

[[namespacePrefixesNamesTable]]
.Namespace prefixes & names
[cols="^.^5%,.^25%,.^70%",]
[%noheader]
|===
|*Prefix* ^|*Name* ^|*Description*
| -- |
urn:oasis:names:specification:ubl:schema:xsd:PriorInformationNotice-2

urn:oasis:names:specification:ubl:schema:xsd:ContractNotice-2

urn:oasis:names:specification:ubl:schema:xsd:ContractAwardNotice-2

|No namespace prefix for the root element

|*cac*
|urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2
|Covers all UBL common aggregated components

|*cbc*
|urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2
|Covers all UBL common basic components

|*ext*
|urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2
|Covers all UBL common extension components

|*efext* |http://eforms/v1.0/Extensions |Covers all eForms specific
extension components

|*efac* |http://eforms/v1.0/ExtensionAggregateComponents |Covers all
eForms specific extension aggregate components

|*efbc* |http://eforms/v1.0/ExtensionBasicComponents |Covers all eForms
specific extension basic components
|===

[[versioningSection]]
== Versioning

The versioning is based on the following scheme:

[.text-center]
*eforms-sdk-x.y.z*

where:

* "**eforms-sdk-**": fixed prefix,

* "**x**": major version number (increased every time backward
compatibility is affected),

* "**y**": minor version number,

* "**z**": rules tuning related number.

Any new release with affected backward compatibility leads to:

* an increment of the major version number, and

* a restart of the minor version numbering.

Major version numbering starts from one, while minor version numbering
starts from zero.

The whole set (i.e. schema and associated rules) will be available for
download and uniquely identified with the above proposed scheme; for
given "**x**" and "**y**", the set with the highest "**z**" value (i.e.
the latest available set) should be used.

Rules tuning will not affect backward compatibility, hence in the XML
instance only the major and minor version numbers will be reported.

Reference to the version inside the XML instance should be limited to
the following expression:

[.text-center]
*eforms-sdk-x.y*
