= Terms & definitions

[glossary]

Admissible tender::
A tender which:
* is from a non-excluded tenderer meeting the selection
criteria,
* conforms with the technical specifications,
* is regular (e.g. submitted on time, normal price & cost, ...),
acceptable, and suitable.

CELEX number::
Identifier assigned at EUR-Lex to documents regardless of the language they are written in. A short presentation may be found at https://eur-lex.europa.eu/content/help/faq/celex-number.html[https://eur-lex.europa.eu/content/help/faq/celex-number.html].

Central Purchasing Body:: 
"A procuring entity that provides
centralised purchasing activities and, possibly, ancillary purchasing
activities for other procuring entities." (eProcurement Ontology)

Concession directive:: 
Directive 2014/23/EU of the European Parliament
and of the Council of 26 February 2014 on the award of concession
contracts, Text with EEA relevance <<dir23>>

Defence directive:: 
Directive 2009/81/EC of the European Parliament
and of the Council of 13 July 2009 on the coordination of procedures for
the award of certain works contracts, supply contracts and service
contracts by contracting authorities or entities in the fields of
defence and security, and amending Directives 2004/17/EC and 2004/18/EC
(Text with EEA relevance) <<dir81>>

General directive:: 
Directive 2014/24/EU of the European Parliament
and of the Council of 26 February 2014 on public procurement and
repealing Directive 2004/18/EC Text with EEA relevance <<dir24>>

Joint procurement::
Combined procurement actions of two or more contracting authorities with
a single call for competition published on behalf of all participating
authorities.
+
Further information may be found on the
https://ec.europa.eu/environment/gpp/pdf/toolkit/module1_factsheet_joint_procurement.pdf[EC
factsheet].

Legal regime::
A system of principles and rules governing something, and which is
created by law. It is framework of legal rules.
(https://definitions.uslegal.com/l/legal-regime/[https://definitions.uslegal.com/l/legal-regime/])
There are two regimes defined for eForms: _standard regime_, and _social regime_.

Part::
"PIN only" (prior information notice used only for information)
component, that, at launch of the call for competition, may become a Lot
or a self-standing Procedure.

Procurement procedure::
Series of actions conducted in a given sequence that leads to the
conclusion of a public contract. The purpose is threefold:
* To guarantee the widest possible participation of economic operators;
* To ensure the transparency of operations; and
* To obtain the desired quality of services, supplies and works at the best possible price.
+
Offers submitted in the context of a procurement procedure are called
"tenders". An economic operator who has submitted a tender is referred
to as a "tenderer".

Qualification System::
To be defined

Sectoral directive::
Directive 2014/25/EU of the European Parliament
and of the Council of 26 February 2014 on procurement by entities
operating in the water, energy, transport and postal services sectors
and repealing Directive 2004/17/EC, Text with EEA relevance <<dir25>>
