// Date and revision are not needed...
:date: 20 May 2021
:revision: 1.2

////
// No need for inline TOC
:toc: left
:toc-title: Contents
:toclevels: 3
////

:imagesdir: ../images
:figure-caption: Figure
:table-caption: Table

:section-refsig: ยง

:xrefstyle: short
:page-toclevels: -1

= Codelists in eForms
[[homeSection]]


== Vocabularies

The Publications Office of the European Union (OP) has defined and published 
many vocabularies for use across a wide range of sectors on the 
 https://op.europa.eu/en/web/eu-vocabularies/controlled-vocabularies[EU Vocabularies]
website.

A subset of these vocabularies are relevant to the domain of eProcurement; 
most of these 
are flat lists of terms and their definitions; some, such as the NUTS 
(Nomenclature of Territorial Units for Statistics) are hierarchical 
taxonomies. They are listed on the  
https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tables[Authority tables and taxonomies used in eProcurement]
page.

== Codelists

A codelist is a flat (non-hierarchical) implementation of a vocabulary: a 
list of language-independent codes that represent an agreed set of values 
for a particular data context. 


== Codelists in eForms

Codelists are used in eForms Notice XML files to restrict the values of some 
data items. Each code has a short label. The majority of codelists also have 
descriptions in each of the 24 official EU languages for every code. 
Codelists for language- or geographic-dependent codes, such as the NUTS 
codes, do not have such translations.

=== Format of codelists

https://op.europa.eu/en/web/eu-vocabularies/controlled-vocabularies[EU Vocabularies]
provides the codelists in a number of different formats for use in different
applications. The format chosen for use in the eForms SDK is the 
http://docs.oasis-open.org/codelist/cs-genericode-1.0/doc/oasis-code-list-representation-genericode.html[OASIS Genericode]
XML format, which was designed for the interchange of machine-readable codelists.

=== Types of codelists

There are three types of codelist used in eForms, based on their source and 
applicability:

* Entire codelists from the EU Vocabularies site

* Tailored codelists

* Technical codelists


==== Entire codelists

These are eProcurement codelists published and maintained on the 
https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tables[Authority tables and taxonomies used in eProcurement]
page of EU Vocabularies. They are used as provided, no changes are made, and 
all codes are available for use in the relevant eForms XML elements. 
The canonical source of these codelists is the EU Vocabularies website.

==== Tailored codelists

Where only a subset of codes included in an eProcurement codelist are allowed 
or applicable in a particular eForms context, a new tailored codelist has 
been created with only those codes. The labels and translations for these 
codes in 
these tailored codelists are the same as in the "parent" eProcurement 
codelists. Since these codelists have no relevance or use outside the 
context of eForms, they are not published on the EU Vocabularies website, but 
are published as part of the https://github.com/OP-TED/eForms-SDK[eForms SDK].

==== Technical codelists

The UBL schema was chosen to define the XML structure for eforms Notices due 
to its wide use for representing business documents across many domains, and 
its very close match to eForms data requirements. However, there are some 
contexts where the UBL elements available are not sufficient to represent the 
Business Terms needed by the context. In these cases new codelists have been 
created to implement the required Business Terms. These technical codelists 
are also published in the https://github.com/OP-TED/eForms-SDK[eForms SDK].


== Codelists in eForms Notice XML

In eForms XML, codes and codelists are mostly referenced using elements 
designed for that purpose. The elements have names which end in "Code", and 
have the attribute "listName". This attribute is used to hold the name of 
the codelist, and the code value required is set as the content of the 
element. In eForms, only codes from one codelist are allowed for any 
specific element.

The example below shows an example of using the code value "supplies" from 
the https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/contract-nature["contract-nature"] 
codelist.

[source, xml]
----
<cbc:ProcurementTypeCode listName="contract-nature">supplies</cbc:ProcurementTypeCode>
----

=== Validation codes and codelists in XML Notices

The validating Schematron rules that are included as part of the 
https://github.com/OP-TED/eForms-SDK[eForms SDK] contain rules 
to validate the correct use of codelists in a Notice XML file. The 
rules check that for each element which should reference a code:

* That the correct codelist is named in the "listName" attribute
* That the content of the element is one of the codes from that codelist


