site:
  title: eForms SDK
  start_page: eforms::index.adoc
content:
  edit_url: false
  sources:
  - url: https://github.com/OP-TED/eForms-SDK.git
    start_path: docs
    branches: main
ui:
  bundle:
    url: https://github.com/OP-TED/antora-eui/releases/download/ui-bundle/eForms-SDK-customisations/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui